-- ============================================================
-- SEED 005.72/79 | rows 7101–7200 of 7867
-- Source: Tabel_Penduduk.csv | Idempotent via ON CONFLICT
-- ============================================================

insert into public.warga
  nik,
  nama,
  tempat_lahir,
  tanggal_lahir,
  jenis_kelamin,
  agama,
  status_perkawinan,
  pekerjaan,
  kewarganegaraan,
  no_kk,
  alamat,
  rt,
  rw,
  dusun,
  desa,
  kecamatan,
  kabupaten,
  provinsi,
  no_hp,
  pendidikan,
  status_dalam_kk,
  pendapatan_bulan,
  suku,
  kepemilikan_rumah,
  luas_rumah,
  jumlah_lantai,
  jenis_lantai,
  jenis_dinding,
  jenis_atap,
  kepemilikan_tanah,
  luas_tanah,
  penerangan,
  sumber_energi_masak,
  mck,
  sumber_air,
  bantuan_sosial,
  bantuan_extra,
  bpjs_kesehatan,
  bpjs_ketenagakerjaan,
  kepemilikan_aset,
  kondisi_fisik,
  nama_ibu,
  nama_bapak,
  golongan_darah
values
  ('5203080810140004',
    'Evan Dimas',
    'Pringgabaya',
    '2014-10-08',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082602180004',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hanaria',
    'M. Yunus',
    'B'),
  ('5203084704880006',
    'Mariom',
    'Labuhan Lombok',
    '1988-04-07',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082602180011',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '24',
    '1',
    'Semen',
    'Papan',
    'Spandek',
    'Numpang',
    '0',
    'Non PLN',
    'Kayu Bakar',
    'Numpang',
    'Mata Air',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Ramli',
    'Amaq Ramli',
    'B'),
  ('5203085005130005',
    'Epita Zahirin',
    'Puyung',
    '2013-05-10',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082602180012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Nadia Amisa',
    'Haerul Gustriadi',
    'O'),
  ('5203104704010007',
    'Nadia Amisa',
    'Genteng',
    '2001-04-07',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082602180012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Sahraeni',
    'Junaidi',
    'O'),
  ('5203081608900001',
    'Haerul Gustriadi',
    'Labuhan Lombok',
    '1990-08-16',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Karyawan BUMN/BUMD',
    'Indonesia',
    '5203082602180012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '2000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Syaitun',
    'Musripun',
    'A'),
  ('5203082606200005',
    'Juniardi Tiyo Nadriansyah',
    'Selong',
    '2020-06-26',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082602180012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Nadia Amisa',
    'Haerul Gustriadi',
    'AB'),
  ('5203086309140002',
    'Zahra Titania Ermil',
    'Pringgabaya',
    '2014-09-23',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082602200009',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Erna Septiana',
    'Er Doni',
    'B'),
  ('5203084112100004',
    'Sahan Aurel Titania',
    'Labuhan Lombok',
    '2010-12-01',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082602200009',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Erna Septiana',
    'Er Doni',
    'A'),
  ('5203085801080004',
    'Putri Zulaeka Rifera',
    'Samarinda',
    '2008-01-18',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082602200009',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Erna Septiana',
    'Er Doni',
    'O'),
  ('5203084609880003',
    'Erna Septiana',
    'Labuhan Lombok',
    '1988-09-06',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Pedagang',
    'Indonesia',
    '5203082602200009',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Zaitun',
    'Musripun',
    'B'),
  ('5203080802110002',
    'Heru Harianto',
    'Pringgabaya',
    '2011-02-08',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082603120018',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Rion Hariyono',
    'Amaq Rion Hariyono',
    'O'),
  ('5203085701040002',
    'Rini Julita',
    'Labuhan Lombok',
    '2004-01-17',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082603120018',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Rion Hariyono',
    'Amaq Rion Hariyono',
    'B'),
  ('5203087112760188',
    'Inaq Rion Hariyono',
    'Tembeng Putek',
    '1976-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203082603120018',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Jannah',
    'Amaq Jannah',
    'O'),
  ('5203083112750312',
    'Amaq Rion Hariyono',
    'Prina',
    '1975-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082603120018',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Ari',
    'Amaq Ari',
    'A'),
  ('5203082509770001',
    'Pahlan',
    'Labuhan Lombok',
    '1977-09-25',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082603120036',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Mahran',
    'Amaq Umbu',
    'O'),
  ('5203083112620167',
    'Amaq Suku',
    'Labuhan Lombok',
    '1962-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082603120042',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '24',
    '1',
    'Semen',
    'Papan',
    'Spandek',
    'Numpang',
    '0',
    'Non PLN',
    'Kayu Bakar',
    'Numpang',
    'Mata Air',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Makdah',
    'Amaq Makdah',
    'AB'),
  ('5203084703940003',
    'Asmaeli',
    'Labuhan Lombok',
    '1994-03-07',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082603120060',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Su',
    'Amaq Rohim',
    'O'),
  ('5203083112600321',
    'Amaq Rohim',
    'Labuhan Lombok',
    '1960-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh',
    'Indonesia',
    '5203082603120060',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Dimah',
    'Amaq Dimah',
    'B'),
  ('5203080502700003',
    'Amaq Irpan',
    'Labuhan Lombok',
    '1970-02-05',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203082603120061',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Nasri',
    'Amaq Nasri',
    'B'),
  ('5203087112730187',
    'Inaq Bukri',
    'Sakra',
    '1973-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203082603120063',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Nurmah',
    'Amaq Nurmah',
    'O'),
  ('5203081206000011',
    'Irli',
    'Labuhan Lombok',
    '2000-06-12',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082603150005',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Jamilah',
    'Mardi',
    'B'),
  ('5203084203820007',
    'Jamilah',
    'Labuhan Lombok',
    '1982-03-02',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Petani',
    'Indonesia',
    '5203082603150005',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Jenah',
    'Samiun',
    'A'),
  ('5203080103020008',
    'Rudi',
    'Labuhan Lombok',
    '2002-03-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082603150006',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Jamiah',
    'Harman',
    'O'),
  ('5203081008170002',
    'Muhammad Arya Ammar',
    'Pringgabaya',
    '2017-08-10',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082603150008',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Helda Apriani',
    'M. Tamzil',
    'O'),
  ('5203084812130001',
    'Bq. Yasmin Eka Wirda',
    'Labuhan Lombok',
    '2013-12-08',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082603150008',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Helda Apriani',
    'Lalu Yakup',
    'A'),
  ('5203085004930006',
    'Helda Apriani',
    'Labuhan Lombok',
    '1993-04-10',
    'Perempuan',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082603150008',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Saeni',
    'Harun Arrasit',
    'B'),
  ('5203081511890002',
    'M. Tamzil',
    'Labuhan Lombok',
    '1989-11-15',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082603150008',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Muriah',
    'Amaq Muhir',
    'B'),
  ('5203085804170004',
    'Baiq Suci Harianto',
    'Selong',
    '2017-04-18',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082604130016',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Zahrani',
    'Lalu Harianto',
    'A'),
  ('5203085012140004',
    'Baiq Annisa Harianto',
    'Pancor',
    '2014-12-10',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082604130016',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Zahrani',
    'Lalu Harianto',
    'O'),
  ('5203080112890002',
    'Lalu Harianto',
    'Mataram',
    '1989-12-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Karyawan Swasta',
    'Indonesia',
    '5203082604130016',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'Diploma',
    'Kepala Keluarga',
    '2000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Inaq Suparlan',
    'Mamiq Suparlan',
    'B'),
  ('5203170107590280',
    'Nursamat',
    'Tanjung',
    '1959-07-01',
    'Laki-Laki',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203082604180003',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '24',
    '1',
    'Semen',
    'Papan',
    'Spandek',
    'Numpang',
    '0',
    'Non PLN',
    'Kayu Bakar',
    'Numpang',
    'Mata Air',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Maisah',
    'Mangsur',
    'O'),
  ('5203082909160002',
    'Ammar Faiz Abdillah',
    'Labuhan Lombok',
    '2016-09-29',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082605100011',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Nety Chandra Wirawati',
    'Eko Handoyo',
    'A'),
  ('5203082610100002',
    'Abdillah Furqon Nabil',
    'Selong',
    '2010-10-26',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082605100011',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Nety Chandra Wirawati',
    'Eko Handoyo',
    'O'),
  ('5203084904060002',
    'Eneysa Maulidiyah Zahira',
    'Labuhan Lombok',
    '2006-04-09',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082605100011',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Nety Chandra Wirawati',
    'Eko Handoyo',
    'O'),
  ('5203082004810002',
    'Eko Handoyo',
    'Jombang',
    '1981-04-20',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'POLRI',
    'Indonesia',
    '5203082605100011',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '2000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Murtining',
    'Triman',
    'B'),
  ('5203086204800004',
    'Nety Chandra Wirawati',
    'Labuhan Lombok',
    '1980-04-22',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082605100011',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Rohana',
    'Hermanto',
    'A'),
  ('5203080201830003',
    'M. Ali Ramdani',
    'Rote',
    '1983-01-02',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203082605100022',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Gesmani Engge',
    'Laban Engge',
    'O'),
  ('5203085005920004',
    'Mei Lia Hastuti',
    'Labuhan Lombok',
    '1992-05-10',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082605100023',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sakmah',
    'Sayuti',
    'AB'),
  ('5203081703620001',
    'Sayuti',
    'Labuhan Lombok',
    '1962-03-17',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082605100023',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Iq Uti',
    'Aq Uti',
    'A'),
  ('5203083112350050',
    'Ismail',
    'Labuhan Lombok',
    '1935-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203082605150016',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Numpang',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Numpang',
    '400',
    'PLN',
    'Kayu Bakar',
    'Sendiri',
    'Perpipaan',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Ismail',
    'Amaq Ismail',
    'O'),
  ('5203065503910003',
    'Muliani',
    'Labuhan Lombok',
    '1991-03-15',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082605150031',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Salmah',
    'Mustakim',
    'B'),
  ('5203086801970003',
    'Yani Tri Ramadhani',
    'Jember',
    '1997-01-28',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082605150036',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mariani',
    'Iman Supriono',
    'B'),
  ('5203081011860011',
    'Supriadi',
    'Pl. Makaran Ganan',
    '1986-11-10',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082605150036',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sri Amah',
    'Zaenal Abidin',
    'A'),
  ('5203086711060005',
    'Hernawati',
    'Teko Lauk',
    '2006-11-27',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082605150039',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sartini',
    'Sariyun',
    'AB'),
  ('5203082302030003',
    'Heri Yanto',
    'Teko Lauk',
    '2003-02-23',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082605150039',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sartini',
    'Sariyun',
    'B'),
  ('5203085005720002',
    'Sartini',
    'Teko Lauk',
    '1972-05-10',
    'Perempuan',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082605150039',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Sartini',
    'Amaq Sartini',
    'B'),
  ('5203083112430082',
    'H. Karni',
    'Dasan Tapen',
    '1943-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082605150039',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '24',
    '1',
    'Semen',
    'Papan',
    'Spandek',
    'Numpang',
    '0',
    'Non PLN',
    'Kayu Bakar',
    'Numpang',
    'Mata Air',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Imran',
    'Amaq Imran',
    'O'),
  ('5203087112440036',
    'Inaq Mahyudin',
    'Labuhan Lombok',
    '1944-12-31',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203082605150040',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '24',
    '1',
    'Semen',
    'Papan',
    'Spandek',
    'Numpang',
    '0',
    'Non PLN',
    'Kayu Bakar',
    'Numpang',
    'Mata Air',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Mahnim',
    'Amaq Mahnim',
    'A'),
  ('5203080310150001',
    'Munirul Arifin',
    'Labuhan Lombok',
    '2015-10-03',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082606120018',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ernawati',
    'Jumaedi',
    'A'),
  ('5203082005110004',
    'Muhamat Hajir',
    'Pringgabaya',
    '2011-05-20',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082606120018',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ernawati',
    'Jumaedi',
    'O'),
  ('5203081904000003',
    'Arsin Al Ghifari',
    'Labuhan Lombok',
    '2000-04-19',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082606120047',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Suburiah',
    'Salman Alfarisi',
    'AB'),
  ('5203083012790016',
    'Yusuf Wijaya',
    'Pringgabaya',
    '1979-12-30',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082606120048',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Herawati',
    'Harsono',
    'B'),
  ('5203081411190004',
    'Muhammad Raffi',
    'Pringgabaya',
    '2019-11-14',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082606120090',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Zubaedah',
    'Hery Purwanto',
    'A'),
  ('7310014107760169',
    'Suhaeba',
    'P Salius Besar',
    '1976-07-01',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082606180009',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Tanni',
    'Badaruddin',
    'O'),
  ('7310010107760177',
    'Maswada',
    'P Salius Besar',
    '1955-07-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082606180009',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Samaria',
    'Hartani',
    'B'),
  ('5203087012630002',
    'Masni',
    'Labuhan Lombok',
    '1963-12-30',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203082607100056',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Riah',
    'Dahri',
    'O'),
  ('5203080107601187',
    'M. Said',
    'Labuhan Lombok',
    '1960-07-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082607100056',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hariah',
    'Baso',
    'O'),
  ('5203082210170006',
    'Muhammad Ilham Hatta Al Fatir',
    'Pringgabaya',
    '2017-10-22',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082607120017',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhapsah',
    'Ibrahim Saputra',
    'A'),
  ('5203080206060006',
    'Rahmad Junaedi',
    'Labuhan Lombok',
    '2006-06-02',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082607120017',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhapsah',
    'Herman',
    'B'),
  ('5203085507020012',
    'Nur''Aeni',
    'Labuhan Lombok',
    '2002-07-15',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082607120017',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhapsah',
    'Herman',
    'O'),
  ('5203085306760005',
    'Nurhapsah',
    'Labuhan Lombok',
    '1976-06-13',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Wiraswasta',
    'Indonesia',
    '5203082607120017',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Unin',
    'Amin',
    'A'),
  ('5203086007070008',
    'Ayu Larasti',
    'Labuhan Lombok',
    '2007-07-20',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082607120022',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhayati',
    'Nasarudin',
    'B'),
  ('5203080912180002',
    'Alvin Opandio Maulana',
    'Labuhan Lombok',
    '2018-12-09',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082607180008',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rosdiana',
    'Hamdani',
    'O'),
  ('5203080201990006',
    'Hamdani',
    'Labuhan Lombok',
    '1999-01-02',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082607180008',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '50',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Numpang',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Munisah',
    'Mahmud',
    'B'),
  ('5203080406200001',
    'Pahmi Ramadani',
    'Pringgabaya',
    '2020-06-04',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082607180008',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rosdiana',
    'Hamdani',
    'A'),
  ('5203082806180003',
    'Rizal Ardiyansah',
    'Selong',
    '2018-06-28',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082609120028',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sopiatun',
    'Muhamad Rozi',
    'O'),
  ('5203085507890018',
    'Sopiatun',
    'Labuhan Lombok',
    '1989-07-15',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082609120028',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Hinun',
    'Amaq Ibrahim',
    'O'),
  ('5203080107841642',
    'Muhamad Rozi',
    'Pringgabaya',
    '1984-07-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203082609120028',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Muhamad Rozi',
    'Amaq Muhamad Rozi',
    'O'),
  ('5203081507040013',
    'Aldi Andriansyah',
    'Labuhan Lombok',
    '2004-07-15',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082609120138',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Johariah',
    'Ali Napiah',
    'B'),
  ('5203081507720007',
    'Ali Napiah',
    'Labuhan Lombok',
    '1972-07-15',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082609120138',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '300',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Ma. Jamiah',
    'Wa. Napiah',
    'A'),
  ('5203085112010003',
    'Baiq Lasmining Puri',
    'Labuhan Lombok',
    '2001-11-11',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082609120139',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Lale Naning Suarni',
    'Lalu Buhari Muslim',
    'A'),
  ('5203087009620001',
    'Mukmin',
    'Labuhan Lombok',
    '1962-09-30',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Pedagang',
    'Indonesia',
    '5203082609120147',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Mukmin',
    'Amaq Mukmin',
    'B'),
  ('5203080104790006',
    'Asror Hamidi',
    'Surabaya',
    '1979-04-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082609120148',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rohana',
    'Hermanto',
    'A'),
  ('5203083112500277',
    'Hermanto',
    'Lumajang',
    '1950-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082609120148',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sumiatun',
    'Srimun',
    'O'),
  ('5203085502190003',
    'Jauza'' Hilya Nuha',
    'Aikmel',
    '2019-02-15',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082609180003',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Halwati',
    'Nursaidni',
    'A'),
  ('5203096503940001',
    'Halwati',
    'Kalijaga Timur',
    '1994-03-25',
    'Perempuan',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082609180003',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'S1/Sarjana',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Husnan',
    'Jamaluddin',
    'O'),
  ('5203083112890150',
    'Nursaidni',
    'Labuhan Lombok',
    '1988-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082609180003',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'S1/Sarjana',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sukiani',
    'Amaq Hadirin',
    'A'),
  ('5203080110940003',
    'Abdurrahman',
    'Labuhan Lombok',
    '1994-10-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082610110052',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mihram',
    'Tuku',
    'A'),
  ('5203087112520037',
    'Mihram',
    'Labuhan Lombok',
    '1952-12-31',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Pedagang',
    'Indonesia',
    '5203082610110052',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Marni',
    'Amaq Marni',
    'B'),
  ('5203082007890003',
    'Junaedi',
    'Labuhan Lombok',
    '1989-07-20',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082610110053',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Zubaedah',
    'Lalu Burhanudin',
    'O'),
  ('5203087112610059',
    'Zubaedah',
    'Labuhan Lombok',
    '1961-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082610110053',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Diasih',
    'Abdul Hamid',
    'O'),
  ('5203080109980004',
    'Roni Simawandi',
    'Labuhan Lombok',
    '1998-09-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082610110066',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Saeah',
    'Sidah',
    'AB'),
  ('5203083008650001',
    'Sidah',
    'Suradadi',
    '1965-08-30',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082610110066',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Ijah',
    'Amaq Sidah',
    'O'),
  ('5203085806770002',
    'Sakmah',
    'Tembeng Putek',
    '1977-06-18',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203082610110087',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Saat',
    'Marihin',
    'A'),
  ('5203082707730002',
    'Burhannudin',
    'Kp. Mandar',
    '1973-07-27',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082610110087',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Maq Isah',
    'Waq Hasan',
    'O'),
  ('5203086412180006',
    'Shakila Shidqi Wahyudi',
    'Labuhan Lombok',
    '2018-12-24',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082610150004',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hesti Ardila',
    'Wahyudi',
    'B'),
  ('5203086608150001',
    'Naura Wahyudi Rahmatillah',
    'Labuhan Lombok',
    '2015-08-26',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082610150004',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hesti Ardila',
    'Wahyudi',
    'O'),
  ('5203084403920001',
    'Hesti Ardila',
    'Labuhan Lombok',
    '1992-03-04',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082610150004',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Siti Fatimah',
    'Nur Abah',
    'AB'),
  ('5203082404900007',
    'Wahyudi',
    'Labuhan Lombok',
    '1990-05-25',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082610150004',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Rusnah',
    'Mulyono Amin',
    'O'),
  ('5203081812990003',
    'Samsul Bahri',
    'Kalimantan',
    '1999-12-18',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082610150009',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Aisah',
    'Mulyadi',
    'O'),
  ('5203081606000008',
    'M. Salihun',
    'Labuhan Lombok',
    '2000-06-16',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082610200004',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '50',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Numpang',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Misnah',
    'Amaq Saedah',
    'O'),
  ('5203054207990005',
    'Eva Susilawati',
    'Masbagik',
    '1999-07-02',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082610200004',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ma''Iyah',
    'Basri',
    'A'),
  ('5203084611170003',
    'Dea Annisa',
    'Pringgabaya',
    '2017-11-06',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082611120030',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Silam',
    'Sahi Mardan',
    'AB'),
  ('5203104107850278',
    'Silam',
    'Dadap',
    '1985-07-01',
    'Perempuan',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203082611120030',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mamah',
    'Senam',
    'A'),
  ('5203080505740004',
    'Sahi Mardan',
    'Labuhan Lombok',
    '1974-05-05',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082611120030',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Rehana',
    'Pahuri',
    'O'),
  ('5203081209130004',
    'Daffa Ibnu Hafiz',
    'Labuhan Lombok',
    '2013-09-12',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082611120044',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Baiq Harpaini',
    'Moh. Jamil',
    'O'),
  ('5203087112930289',
    'Suharni',
    'Pringgabaya',
    '1993-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082611130014',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sarinah',
    'Amaq Ayuni',
    'B'),
  ('5203081608980006',
    'Khaerul Azmi',
    'Labuhan Lombok',
    '1998-08-16',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082611150003',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Cucu',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Jumariah',
    'M. Amin',
    'AB'),
  ('5203084107450567',
    'Bakyah',
    'Labuhan Lombok',
    '1945-07-01',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203082611150003',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '24',
    '1',
    'Semen',
    'Papan',
    'Spandek',
    'Numpang',
    '0',
    'Non PLN',
    'Kayu Bakar',
    'Numpang',
    'Mata Air',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Damah',
    'Data',
    'A'),
  ('5203082510130003',
    'Lifaldi',
    'Pringgabaya',
    '2013-10-25',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082611150015',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Eli Diana Sari',
    'Muhamad Saleh',
    'B')
on conflict (nik) do update set
  updated_at = now();
