-- ============================================================
-- SEED 005.08/79 | rows 701–800 of 7867
-- Source: Tabel_Penduduk.csv | Idempotent via ON CONFLICT
-- ============================================================

insert into public.warga
  nik,
  nama,
  tempat_lahir,
  tanggal_lahir,
  jenis_kelamin,
  agama,
  status_perkawinan,
  pekerjaan,
  kewarganegaraan,
  no_kk,
  alamat,
  rt,
  rw,
  dusun,
  desa,
  kecamatan,
  kabupaten,
  provinsi,
  no_hp,
  pendidikan,
  status_dalam_kk,
  pendapatan_bulan,
  suku,
  kepemilikan_rumah,
  luas_rumah,
  jumlah_lantai,
  jenis_lantai,
  jenis_dinding,
  jenis_atap,
  kepemilikan_tanah,
  luas_tanah,
  penerangan,
  sumber_energi_masak,
  mck,
  sumber_air,
  bantuan_sosial,
  bantuan_extra,
  bpjs_kesehatan,
  bpjs_ketenagakerjaan,
  kepemilikan_aset,
  kondisi_fisik,
  nama_ibu,
  nama_bapak,
  golongan_darah
values
  ('5203080107961434',
    'Muhammad Pauzi Azhar',
    'Lepek Loang',
    '1997-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080711120077',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sayuti Anwar',
    'Anwar',
    'A'),
  ('5203087112730316',
    'Sayuti Anwar',
    'Lepak',
    '1973-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080711120077',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Suhirman',
    'Amaq Suhirman',
    'AB'),
  ('5203080107681130',
    'Haeril Anwar',
    'Labuhan Lombok',
    '1968-07-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203080711120077',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Masitah',
    'Amaq Masitah',
    'A'),
  ('5203085809090005',
    'Anisa Padila',
    'Labuhan Lombok',
    '2007-09-18',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080509740003',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Juliana',
    'Alimudin',
    'O'),
  ('5203085008730007',
    'Juliana',
    'Labuhan Lombok',
    '1973-08-10',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080509740003',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Aminullah',
    'Papuq Aminullah',
    'B'),
  ('5203081408160003',
    'M. Latipul Hobir',
    'Labuhan Lombok',
    '2016-08-14',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080711120099',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Radiah',
    'Satolah',
    'A'),
  ('5203082111070001',
    'Ahmad Kalam',
    'Labuhan Lombok',
    '2007-11-21',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080711120099',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Radiah',
    'Satolah',
    'A'),
  ('5203085109850002',
    'Radiah',
    'Labuhan Lombok',
    '1985-09-11',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080711120099',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sakmah',
    'Ncok Muhidin',
    'O'),
  ('5203082709770003',
    'Satolah',
    'Labuhan Lombok',
    '1977-09-27',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080711120099',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Jenah',
    'Samiun',
    'B'),
  ('5203084509150002',
    'Widia Agustina',
    'Pringgabaya',
    '2015-09-05',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082803120034',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Beton',
    'Sendiri',
    '300',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ani',
    'Junaedi',
    'A'),
  ('5203084103110001',
    'Nadia Ratna Ayu',
    'Pringgabaya',
    '2011-03-01',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081906100033',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ani',
    'Junaedi',
    'B'),
  ('5203080808070006',
    'M. Abdurrahman Zikri',
    'Labuhan Lombok',
    '2007-08-08',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203081906100033',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ani',
    'Junaedi',
    'A'),
  ('5203087112880350',
    'Ani',
    'Tebaban',
    '1988-12-31',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081906100033',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Isah',
    'Mahnur',
    'AB'),
  ('5203083112720421',
    'Junaedi',
    'Rumbuk',
    '1972-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081906100033',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Rusmah',
    'Amaq Haeni',
    'AB'),
  ('5203084905140004',
    'Dinda Ayu Lestari',
    'Labuhan Lombok',
    '2014-05-09',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120056',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Salmah',
    'Kamaludin',
    'B'),
  ('5203087112820405',
    'Salmah',
    'Labuhan Lombok',
    '1982-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080111120056',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Famili Lain',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Beton',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Rida''Ah',
    'Amaq Suma',
    'O'),
  ('5203083112670345',
    'Kamaludin',
    'Tebaban',
    '1967-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082803120028',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Isah',
    'Mahnur',
    'O'),
  ('5203084203150002',
    'Winda Yustari',
    'Pringgabaya',
    '2015-03-02',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080712110018',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rehan',
    'Safa''At',
    'A'),
  ('5203087112810083',
    'Rehan',
    'Labuhan Lombok',
    '1981-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Buruh Tani',
    'Indonesia',
    '5203080712110018',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '5000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mudah',
    'Damsiah',
    'O'),
  ('5203083112610064',
    'Safa''At',
    'Labuhan Lombok',
    '1961-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Transportasi/Ojek/Supir',
    'Indonesia',
    '5203080712110018',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '2500000',
    'Sasak',
    'Sendiri',
    '90',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '300',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Jenah',
    'Samiun',
    'A'),
  ('5203087112720186',
    'Inaq Muksan',
    'Labuhan Lombok',
    '1972-12-31',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Pedagang',
    'Indonesia',
    '5203080712110020',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Mur',
    'Asan',
    'O'),
  ('5203087112640251',
    'Inaq Amrullah',
    'Pancor',
    '1964-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080706140001',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Katemi',
    'Amaq Sipaen',
    'B'),
  ('5203080506170001',
    'Ahmad Ali Ramadhan',
    'Pringgabaya',
    '2017-06-05',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080712120059',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Agustina',
    'Hendra',
    'AB'),
  ('5203083103100006',
    'Rizal Abdi Sanjaya',
    'Labuhan Lombok',
    '2010-03-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080712120059',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Agustina',
    'Hendra',
    'B'),
  ('5203086303060004',
    'Vina Mely Apriani',
    'Labuhan Lombok',
    '2006-03-23',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080712120059',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Agustina',
    'Hendra',
    'A'),
  ('5203085208860003',
    'Agustina',
    'Labuhan Lombok',
    '1986-08-12',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080712120059',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sitiara',
    'Makmur',
    'O'),
  ('5203080910810004',
    'Hendra',
    'Labuhan Lombok',
    '1981-10-09',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080712120059',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '3000000',
    'Sasak',
    'Sendiri',
    '54',
    '1',
    'Keramik',
    'Bata',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Raodah',
    'Halifah',
    'A'),
  ('5203081512190001',
    'Khairil Padly',
    'Pringgabaya',
    '2019-12-15',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080712120059',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Agustina',
    'Hendra',
    'O'),
  ('5203085203120003',
    'Lidia Arniansyah',
    'Pringgabaya',
    '2012-03-12',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080712120102',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hernianti',
    'Lalu Hamzah',
    'O'),
  ('5203084107941546',
    'Hernianti',
    'Pringgabaya',
    '1994-07-01',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080712120102',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Halimah',
    'Mustaan',
    'B'),
  ('5203083112820504',
    'Lalu Hamzah',
    'Pringgabaya',
    '1982-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203080712120102',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Daisah',
    'Mamiq Daisah',
    'B'),
  ('5203086310170002',
    'Nurul Ayu Ningsih',
    'Labuhan Lombok',
    '2017-10-23',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082204150212',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Pitriani',
    'Zulkarnaen',
    'B'),
  ('5203083112890244',
    'Faisal',
    'Labuhan Lombok',
    '1989-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203081204120035',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Cindara',
    'Ahmad',
    'A'),
  ('5203084202130007',
    'Ely Febrianingsih',
    'Pringgabaya',
    '2013-02-02',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801130020',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sahtum',
    'Nurahman',
    'A'),
  ('5203084909900006',
    'Sahtum',
    'Labuhan Lombok',
    '1990-09-09',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080801130020',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Mariani',
    'Amaq Budiah',
    'A'),
  ('5203080107861573',
    'Nurahman',
    'Labuhan Lombok',
    '1986-07-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080801130020',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '4000000',
    'Sasak',
    'Sendiri',
    '78',
    '1',
    'Keramik',
    'Bata',
    'Genteng',
    'Sendiri',
    '400',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Nurmin',
    'Amaq Saudi',
    'O'),
  ('5203082509190003',
    'Rifqi Ainurrohman',
    'Pringgabaya',
    '2019-09-25',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801130020',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sahtum',
    'Nurahman',
    'B'),
  ('5203086504140004',
    'Apriliyani',
    'Pringgabaya',
    '2014-04-25',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801130048',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Jumaeni',
    'Nurhamsah',
    'A'),
  ('5203083112870493',
    'Nurhamsah',
    'Labuhan Lombok',
    '1987-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203080801130048',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Rohanah',
    'Amaq Rohanah',
    'O'),
  ('5203084107852243',
    'Jumaeni',
    'Labupandan',
    '1985-07-01',
    'Perempuan',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203080801130048',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Misbah',
    'Amaq Misbah',
    'O'),
  ('5203081603150001',
    'Supriandi',
    'Labuhan Lombok',
    '2015-03-16',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082910120132',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hurul Hamidah',
    'Suandi',
    'B'),
  ('5203087112970163',
    'Hurul Hamidah',
    'Labuhan Lombok',
    '1997-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082910120132',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '50',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Numpang',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Supiah',
    'Amaq Eni',
    'O'),
  ('5203080504850014',
    'Suandi',
    'Labuhan Lombok',
    '1985-04-05',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120100',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Subaedah',
    'Peta Waris',
    'O'),
  ('5203086205180004',
    'Aisyah Adilah',
    'Pringgabaya',
    '2018-05-22',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801150038',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurul Fauziah',
    'Tamrin',
    'B'),
  ('5203083011120004',
    'Muh. Usyaqul Huur Abdurahman',
    'Labuhan Lombok',
    '2012-11-30',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801150038',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurul Fauziah',
    'Tamrin',
    'B'),
  ('5203084102110007',
    'Khaulah Adilah',
    'Labuhan Lombok',
    '2011-02-01',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801150038',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurul Fauziah',
    'Tamrin',
    'O'),
  ('5203086205080001',
    'Fitrah Adilah',
    'Labuhan Lombok',
    '2008-05-22',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801150038',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurul Fauziah',
    'Tamrin',
    'O'),
  ('5203085107060007',
    'Haya Hadilah',
    'Labuhan Lombok',
    '2006-07-11',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801150038',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurul Fauziah',
    'Tamrin',
    'O'),
  ('5203085906830001',
    'Nurul Fauziah',
    'Samarinda',
    '1983-06-19',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080801150038',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sri Sutiyani',
    'Muhammad',
    'O'),
  ('5203083112770480',
    'Tamrin',
    'Labuhan Lombok',
    '1977-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh Nelayan',
    'Indonesia',
    '5203080801150038',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Keramik',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sakka',
    'Hudring',
    'B'),
  ('5203084707180001',
    'Anindia Keisha Azzahra',
    'Pringgabaya',
    '2018-07-07',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801180009',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Husnul Khotimah',
    'Haeroni',
    'B'),
  ('5203082707940004',
    'Haeroni',
    'Pringgabaya',
    '1994-07-27',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh Tani',
    'Indonesia',
    '5203080801180009',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Nurtimah',
    'Umar',
    'A'),
  ('5203085204950005',
    'Husnul Khotimah',
    'Labuhan Lombok',
    '1995-04-12',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080801180009',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Siti Masitah',
    'Jalaludin',
    'O'),
  ('5203082508800002',
    'Samsul Riadi',
    'Labuhan Lombok',
    '1980-08-25',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203080201130063',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Maduhur',
    'Saat',
    'O'),
  ('5203087103150002',
    'Nabila Diandra Putri',
    'Labuhan Lombok',
    '2015-03-31',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080801210007',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mardiana',
    'Hendra',
    'A'),
  ('3327082609820223',
    'Setia Aji',
    'Pemalang',
    '1982-09-26',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080801210007',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Jawa',
    'Sendiri',
    '48',
    '1',
    'Keramik',
    'Bata',
    'Spandek',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Suharti',
    'Tachari',
    'O'),
  ('5203084109130004',
    'Murya',
    'Pringgabaya',
    '2013-09-01',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203087112050029',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Paridah',
    'Jamhur Hakkim',
    'O'),
  ('5203087112050029',
    'Dewi Puspa Sari',
    'Labuhan Lombok',
    '2005-12-31',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203087112050029',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Paridah',
    'Sukri',
    'O'),
  ('5203086703970004',
    'Milna',
    'Labuhan Lombok',
    '1997-03-27',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203087112050029',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Sendiri',
    '24',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Numpang',
    '0',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Paridah',
    'Jamhur Hakkim',
    'O'),
  ('5203083112890216',
    'Isbandi',
    'Labuhan Lombok',
    '1989-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203080802120001',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Paridah',
    'Jamhur Hakkim',
    'O'),
  ('5203083112860250',
    'Mashurrahman',
    'Labuhan Lombok',
    '1986-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203080802120001',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Paridah',
    'Jamhur Hakkim',
    'O'),
  ('5203087112680179',
    'Paridah',
    'Labuhan Lombok',
    '1968-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080802120001',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mahrim',
    'Waq Kadir',
    'B'),
  ('5203083112660135',
    'Jamhur Hakkim',
    'Jantuk',
    '1966-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080802120001',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Masna',
    'Abu Jamhur',
    'B'),
  ('5203086603120003',
    'Rossan Suryana',
    'Labuhan Lombok',
    '2012-03-26',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080802120029',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Istikomah',
    'Wawan Surya Wardani',
    'O'),
  ('5203085202920004',
    'Istikomah',
    'Labuhan Lombok',
    '1992-02-12',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080802120029',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Murni',
    'Sudirman',
    'B'),
  ('5203081711900004',
    'Wawan Surya Wardani',
    'Labuhan Lombok',
    '1990-11-17',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203080802120029',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Zubaedah',
    'Hamdan',
    'B'),
  ('5203083112890217',
    'Nasrullah',
    'Labuhan Lombok',
    '1989-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080802120076',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sarah',
    'Jasrudi',
    'O'),
  ('5203084703890004',
    'Rohida',
    'Labuhan Lombok',
    '1989-03-07',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080802120076',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Audi',
    'Jariyah',
    'B'),
  ('5203082906120004',
    'Muhammad Jumahir',
    'Labuhan Lombok',
    '2012-06-29',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080802130015',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nikmah',
    'Muhammad Sopi',
    'A'),
  ('5203087112920316',
    'Nikmah',
    'Labuhan Lombok',
    '1992-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080802130015',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Rakmah',
    'Amaq Cali',
    'O'),
  ('5203083112900415',
    'Muhammad Sopi',
    'Labuhan Lombok',
    '1990-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080802130015',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '3000000',
    'Sasak',
    'Sendiri',
    '78',
    '1',
    'Keramik',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Stim',
    'Srijuddin',
    'O'),
  ('5203082211190001',
    'Maulana Ali',
    'Selong',
    '2019-11-22',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080802130015',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nikmah',
    'Muhammad Sopi',
    'O'),
  ('5203084509000007',
    'Indah Permata Sari',
    'Labuhan Lombok',
    '2000-09-05',
    'Perempuan',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203080802180013',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sakmah',
    'Sayuti',
    'A'),
  ('5203081111980002',
    'Suriadi Ansyah',
    'Labuhan Lombok',
    '1998-11-11',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080802180013',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hanaria',
    'Lalu Sadri',
    'O'),
  ('5203080902150001',
    'Rizky Budiman',
    'Pringgabaya',
    '2015-02-09',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203130802180015',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Puspawangi',
    'Haji Agus Budiman',
    'A'),
  ('5203132802780003',
    'M. Fajri',
    'Pancor',
    '1978-02-28',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203130802180015',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'Diploma',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Husniah',
    'Sajudin',
    'B'),
  ('5203084907110002',
    'Jema',
    'Labuhan Lombok',
    '2011-07-09',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080800312002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rakmah',
    'Amaq Jeni',
    'B'),
  ('5203080501080001',
    'Jiwan',
    'Labuhan Lombok',
    '2008-01-05',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080800312002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rakmah',
    'Amaq Jeni',
    'O'),
  ('5203080104040010',
    'Jepin',
    'Labuhan Lombok',
    '2004-04-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080800312002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rakmah',
    'Amaq Jeni',
    'O'),
  ('5203080403990004',
    'Jaeni',
    'Labuhan Lombok',
    '1998-04-20',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080800312002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rakmah',
    'Mahrun',
    'O'),
  ('5203087112790190',
    'Rakmah',
    'Labuhan Lombok',
    '1979-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080800312002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Denah',
    'Amaq Sahria',
    'B'),
  ('5203083112770243',
    'Amaq Jeni',
    'Labuhan Lombok',
    '1977-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203080800312002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Papan',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Sakdah',
    'Amaq Jalimah',
    'O'),
  ('5203085005190001',
    'Jesi',
    'Pringgabaya',
    '2019-05-10',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080800312002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rakmah',
    'Amaq Jeni',
    'A'),
  ('5203086508600001',
    'Sumrat',
    'Kalijaga',
    '1960-08-25',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080805120036',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Saiyah',
    'Amaq Saiyah',
    'B'),
  ('5203087112520181',
    'Rabiah',
    'Labuhan Lombok',
    '1952-12-31',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203080805150034',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Sendiri',
    '30',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Numpang',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Simah',
    'Hasan',
    'B'),
  ('5203081111130005',
    'Zio Tanzilal',
    'Pringgabaya',
    '2013-11-11',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203084502880004',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Pibriana Arika Dewi',
    'Muhrad',
    'O'),
  ('5203084502880004',
    'Pibriana Arika Dewi',
    'Labuhan Lombok',
    '1988-02-05',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203084502880004',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Numpang',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Nurfaizah',
    'Samsudin',
    'B'),
  ('5203080701870006',
    'Muhrad',
    'Labuhan Lombok',
    '1987-01-07',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080901870001',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nahadiah',
    'Syahrudin',
    'O'),
  ('5203081205150004',
    'Sofyan Saladin',
    'Selong',
    '2015-05-12',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080806100037',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Miftahul Jannah',
    'Aminullah',
    'O'),
  ('5203086801090001',
    'Fani Apnan Jannati',
    'Labuhan Lombok',
    '2009-01-28',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080806100037',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Miftahul Jannah',
    'Aminullah',
    'B'),
  ('5203084602040002',
    'Nabila Aminarti',
    'Labuhan Lombok',
    '2004-02-06',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080806100037',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Miftahul Jannah',
    'Aminullah',
    'A'),
  ('5203085801810002',
    'Miftahul Jannah',
    'Aikmel',
    '1981-01-18',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080806100037',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Siti Halisah',
    'H.M. Safi''I',
    'A'),
  ('5203080903750002',
    'Aminullah',
    'Labuhan Lombok',
    '1975-03-09',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203080806100037',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Nurhikmah',
    'Japri',
    'O'),
  ('5203081005170002',
    'Dzaky Abdul Hadi',
    'Dames',
    '2017-05-10',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080806150002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Husnita Dewi',
    'Suhayadi',
    'A'),
  ('5271065511960002',
    'Husnita Dewi',
    'Mataram',
    '1996-11-15',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080806150002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mastah',
    'Sahba',
    'B'),
  ('5203083112930334',
    'Suhayadi',
    'Labuhan Lombok',
    '1993-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203080806150002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas PLN',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Amnah',
    'Ahyar Rosidi',
    'B'),
  ('5203080607200001',
    'Azriel Lazuardi',
    'Selong',
    '2020-07-06',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080806150002',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Husnita Dewi',
    'Suhayadi',
    'O'),
  ('5203080102120003',
    'Muh. Haeriyadi',
    'Labuhan Lombok',
    '2012-02-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080861800090',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Musnim',
    'Ridwan',
    'A'),
  ('5203082909080005',
    'Muh. Haerul Anwar',
    'Labuhan Lombok',
    '2008-09-23',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203080861800090',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Musnim',
    'Ridwan',
    'A'),
  ('7310014508900001',
    'Musnim',
    'Labuhan Lombok',
    '1986-08-05',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080861800090',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Sendiri',
    '24',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Numpang',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Muridah',
    'Muhammad',
    'B')
on conflict (nik) do update set
  updated_at = now();
