-- ============================================================
-- SEED PART 16/79 — rows 1501–1600
-- Source: Tabel_Penduduk.csv
-- Idempotent: ON CONFLICT (nik) DO UPDATE SET updated_at = now()
-- ============================================================

insert into public.warga
  nik,
  nama,
  tempat_lahir,
  tanggal_lahir,
  jenis_kelamin,
  agama,
  status_perkawinan,
  pekerjaan,
  kewarganegaraan,
  no_kk,
  alamat,
  rt,
  rw,
  dusun,
  desa,
  kecamatan,
  kabupaten,
  provinsi,
  no_hp,
  pendidikan,
  status_dalam_kk,
  pendapatan_bulan,
  suku,
  kepemilikan_rumah,
  luas_rumah,
  jumlah_lantai,
  jenis_lantai,
  jenis_dinding,
  jenis_atap,
  kepemilikan_tanah,
  luas_tanah,
  penerangan,
  sumber_energi_masak,
  mck,
  sumber_air,
  bantuan_sosial,
  bantuan_extra,
  bpjs_kesehatan,
  bpjs_ketenagakerjaan,
  kepemilikan_aset,
  kondisi_fisik,
  nama_ibu,
  nama_bapak,
  golongan_darah
values
  ('5203080606830004',
    'Nasruddin',
    'Labuhan Lombok',
    '1983-06-06',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Peternak',
    'Indonesia',
    '5203081505120053',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1800000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Keramik',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Nurminah',
    'Saleh',
    'B'),
  ('5203084707000006',
    'Irna',
    'Labuhan Lombok',
    '2000-07-07',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081505180003',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Santi',
    'Sahar',
    'AB'),
  ('5203080104980006',
    'Ulin',
    'Labuhan Lombok',
    '1998-04-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081505180003',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Radiah',
    'Sumakila',
    'A'),
  ('5203084307130002',
    'Aisyah Gina Nur Amalina',
    'Pringgabaya',
    '2013-07-03',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080101670005',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Murniati',
    'Nurdin',
    'O'),
  ('5203084109090002',
    'Aisyah Rizki Ramadani',
    'Labuhan Lombok',
    '2009-09-01',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203080101670005',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Murniati',
    'Nurdin',
    'O'),
  ('5203081009050002',
    'M. Izzudin Al Qossam',
    'Labuhan Lombok',
    '2004-08-12',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203080101670005',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Murniati',
    'Nurdin',
    'A'),
  ('5203081106000001',
    'Jundi Sabilil Firdaus',
    'Labuhan Lombok',
    '2000-06-11',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080101670005',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Murniati',
    'Nurdin',
    'B'),
  ('5203084703970002',
    'Rita Fajri Qomariatul Aisyah',
    'Labuhan Lombok',
    '1997-03-23',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080101670005',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Murniati',
    'Nurdin. S',
    'B'),
  ('5203080101670005',
    'Nurdin',
    'Labuhan Lombok',
    '1967-01-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203080101670005',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Siti Aisyah',
    'M. Said',
    'A'),
  ('5203082003950001',
    'Ilwan Zikri',
    'Labuhan Lombok',
    '1995-03-20',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120013',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Fathaeni',
    'Ilham',
    'O'),
  ('5203080707100003',
    'Edowardi Saputra',
    'Labuhan Lombok',
    '2010-07-07',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081506200024',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Fitriah',
    'Saparudin',
    'O'),
  ('5203086009730001',
    'Fitriah',
    'Labuhan Lombok',
    '1973-09-20',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Lainnya',
    'Indonesia',
    '5203081506200024',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Satar''Ah',
    'Aguswari',
    'O'),
  ('5203084708100004',
    'Amelinda',
    'Labuhan Lombok',
    '2010-08-07',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081508120066',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Jeni',
    'Amaq Sidik',
    'O'),
  ('5203081306070006',
    'Ripaldi',
    'Labuhan Lombok',
    '2007-06-13',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081508120066',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Jeni',
    'Amaq Sidik',
    'B'),
  ('5203085507570010',
    'Inaq Jeni',
    'Liwatan Pucat',
    '1957-07-15',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081508120066',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Jan',
    'Amaq Jan',
    'B'),
  ('5203081507370002',
    'Amaq Sidik',
    'Prina',
    '1937-07-15',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203081508120066',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Mariah',
    'Amaq Mariah',
    'A'),
  ('5203086001160002',
    'Alfia Miftahul Jannah',
    'Pringgabaya',
    '2016-01-20',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081309120015',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sinar Wahida',
    'Rusli Bedu',
    'B'),
  ('5203081108100010',
    'Tegar Ramadan',
    'Labuhan Lombok',
    '2010-08-11',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203081309120015',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sinar Wahida',
    'Rusli Bedu',
    'AB'),
  ('5203083112800664',
    'Rusli Bedu',
    'Kupang',
    '1980-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081309120015',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Labe',
    'Bedu',
    'B'),
  ('5203086505800006',
    'Nurhayati',
    'Labuhan Lombok',
    '1980-05-25',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Pedagang',
    'Indonesia',
    '5203081509120004',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Daiyah',
    'Amaq Daiyah',
    'O'),
  ('5203086012170005',
    'Jihan Kamilia',
    'Selong',
    '2017-12-20',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081307100110',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Asri Febriana',
    'Haris Mugira',
    'O'),
  ('5203085403110001',
    'Faeda Annayla',
    'Labuhan Lombok',
    '2011-03-14',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203081307100110',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Asri Febriana',
    'Haris Mugira',
    'A'),
  ('5203084502900001',
    'Asri Febriana',
    'Labuhan Lombok',
    '1990-02-05',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203081307100110',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hadijah',
    'Alimudin',
    'B'),
  ('5203080302850001',
    'Haris Mugira',
    'Labuhan Lombok',
    '1985-02-03',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203081307100110',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Daimah',
    'Abd. Rasyid',
    'O'),
  ('5203086505120009',
    'Juliani',
    'Pringgabaya',
    '2012-05-25',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120006',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Hadi',
    'Amaq Hadi',
    'O'),
  ('5203080101070012',
    'Al Mahdiki',
    'Labuhan Lombok',
    '2007-01-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120006',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nuriah',
    'Jaenudin',
    'B'),
  ('5203082009770001',
    'Amaq Hadi',
    'Labuhan Lombok',
    '1977-09-20',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Peternak',
    'Indonesia',
    '5203081509120006',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '2400000',
    'Sasak',
    'Sendiri',
    '84',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Nurdin',
    'Amaq Nurdin',
    'B'),
  ('5203085008750005',
    'Inaq Hadi',
    'Labuhan Lombok',
    '1975-08-10',
    'Perempuan',
    'Islam',
    'Kawin',
    'Buruh Tani',
    'Indonesia',
    '5203081509120006',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Imin',
    'Amaq Napiah',
    'B'),
  ('5203082709990007',
    'Afdian Suherwin',
    'Labuhan Lombok',
    '1999-09-27',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120007',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ramnah',
    'Suhaedi',
    'O'),
  ('5203081208740004',
    'Suhaedi',
    'Labuhan Lombok',
    '1974-08-12',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081509120007',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Mahnep',
    'Jamuhur',
    'A'),
  ('5203087112720337',
    'Ramnah',
    'Bayan',
    '1972-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120007',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Nasilam',
    'Amaq Nasilam',
    'O'),
  ('5203083007070003',
    'M. Mashudi',
    'Labuhan Lombok',
    '2007-07-30',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120026',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Budiati',
    'Sulaiman',
    'O'),
  ('5203087112890311',
    'Budiati',
    'Pringgabaya',
    '1989-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203081509120026',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rukaiyah',
    'Amaq Sulaeman',
    'A'),
  ('5203083112870385',
    'Sulaiman',
    'Labuhan Lombok',
    '1987-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081509120026',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Patimah',
    'Wak Suhaemi',
    'A'),
  ('5203083112550231',
    'Wak Suhaemi',
    'Labuhan Lombok',
    '1955-12-31',
    'Laki-Laki',
    'Islam',
    'Cerai Hidup',
    'Nelayan',
    'Indonesia',
    '5203081509120027',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hasiah',
    'Mahruf',
    'O'),
  ('5203080304140001',
    'Baso'' Dimas Hadi',
    'Pringgabaya',
    '2014-04-03',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120028',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Eli Ermawati',
    'Ali Ashar',
    'O'),
  ('5203086811880001',
    'Eli Ermawati',
    'Labuhan Lombok',
    '1988-11-28',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203081509120028',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Fatimah',
    'Wak Suhaemi',
    'O'),
  ('5203083112860388',
    'Ali Ashar',
    'Bone',
    '1986-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081509120028',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hasma',
    'Dg. Masiga',
    'A'),
  ('5203084907120002',
    'Maya Rahma Aditiya',
    'Pringgabaya',
    '2012-07-09',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203081509120029',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Eli Rahmawati',
    'Suhardi',
    'B'),
  ('5203085709060003',
    'Cantika',
    'Labuhan Lombok',
    '2006-09-17',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203081509120029',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sumarni',
    'Suhardi',
    'O'),
  ('5203081010770009',
    'Suhardi',
    'Labuhan Lombok',
    '1977-10-10',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203081509120029',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '150',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Mq. Patimah',
    'Wq. Suhaemi Hr.',
    'B'),
  ('5203081512090002',
    'Gempar Ardiansyah',
    'Labuhan Lombok',
    '2009-12-15',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pedagang',
    'Indonesia',
    '5203082001140022',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sahni',
    'Zaedon',
    'A'),
  ('5203082911960004',
    'Hizban Sadiq',
    'Labuhan Lombok',
    '1996-11-29',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082808120073',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sahni',
    'Zaedon',
    'A'),
  ('5203083112750435',
    'Zaedon',
    'Jantuk',
    '1975-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082808120073',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '36',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Numpang',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Numpang',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Maharni',
    'Zaenal Abidin',
    'O'),
  ('5203087112730273',
    'Sahni',
    'Labuhan Lombok',
    '1973-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082808120073',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Minah',
    'Amaq Alimin',
    'B'),
  ('5203082712120006',
    'Arzaqi Wisnu Syahfi',
    'Selong',
    '2012-12-27',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120067',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Serni Setiawati',
    'Marzuki',
    'O'),
  ('5203080810980005',
    'Achmad Wiranadi Hakim',
    'Labuhan Lombok',
    '1998-10-08',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120067',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Serni Setiawati',
    'Marzuki',
    'B'),
  ('5203082311930004',
    'Ardian Indra Setiawan',
    'Keruak',
    '1993-11-23',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120067',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Serni Setiawati',
    'Marzuki',
    'O'),
  ('5203086008700002',
    'Serni Setiawati',
    'Keruak',
    '1970-08-20',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081509120067',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'Diploma',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Bq. Wisnun',
    'Moh. Syafiuddin',
    'A'),
  ('5203081808050005',
    'Bagus Harudiansyah',
    'Labuhan Lombok',
    '2005-08-18',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081510110005',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sanah',
    'Harun',
    'B'),
  ('5203086604010004',
    'Widia Apriani',
    'Labuhan Lombok',
    '2001-04-26',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081510110005',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'S1/Sarjana',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sanah',
    'Harun',
    'O'),
  ('5203087112740070',
    'Sanah',
    'Labuhan Lombok',
    '1974-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203081510110005',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Iq. Mustinah',
    'Aq. Wahab',
    'AB'),
  ('5203083112700204',
    'Harun',
    'Labuhan Lombok',
    '1970-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh Nelayan',
    'Indonesia',
    '5203081510110005',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Iq. Nursim',
    'Aq. Nursim',
    'O'),
  ('5203083112600523',
    'Sidik',
    'Lengkoq Dudu',
    '1960-12-31',
    'Laki-Laki',
    'Islam',
    'Cerai Hidup',
    'Tidak Bekerja',
    'Indonesia',
    '5203081510120102',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '24',
    '1',
    'Papan',
    'Papan',
    'Daun/Alami',
    'Numpang',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Numpang',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Suut',
    'Amaq Suut',
    'O'),
  ('5203087112070045',
    'Rosada',
    'Labuhan Lombok',
    '2008-08-28',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081511130003',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Erna',
    'Busaeri',
    'O'),
  ('5203083112940251',
    'Mawardi',
    'Labuhan Lombok',
    '1994-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081511130003',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Sul',
    'Amaq Sul',
    'O'),
  ('5203087112710262',
    'Sul',
    'Labuhan Lombok',
    '1971-12-31',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Buruh Tani',
    'Indonesia',
    '5203081511130003',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1300000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Keramik',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Gunisah',
    'Amaq Sahram',
    'A'),
  ('5203080104120005',
    'Muh. Rizal Ajuar',
    'Pringgabaya',
    '2012-04-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081511130005',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sahdan',
    'Muhammad Ali',
    'A'),
  ('5203087112760388',
    'Sahdan',
    'Labuhan Lombok',
    '1976-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203081511130005',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Seban',
    'Amaq Temah',
    'A'),
  ('5203083112670433',
    'Muhammad Ali',
    'Labuhan Lombok',
    '1967-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081511130005',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1300000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Keramik',
    'Bata',
    'Spandek',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Fatimah',
    'Jangak',
    'B'),
  ('5203084811140001',
    'Niken Anjani',
    'Selong',
    '2014-11-08',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081512110047',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Holis',
    'Amaq Warni',
    'A'),
  ('5203084401010002',
    'Selti',
    'Labuhan Lombok',
    '2005-08-29',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081512110047',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Holis',
    'Amaq Warni',
    'A'),
  ('5203087112840192',
    'Inaq Holis',
    'Labuhan Lombok',
    '1984-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081512110047',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Muhamad',
    'Amaq Muhamad',
    'O'),
  ('5203083112710141',
    'Amaq Warni',
    'Labuhan Lombok',
    '1971-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Karyawan Swasta',
    'Indonesia',
    '5203081512110047',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '2000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Keramik',
    'Bata',
    'Spandek',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Inaq Munah',
    'Amaq Munah',
    'O'),
  ('5203084902110004',
    'Naera Sulastri',
    'Labuhan Lombok',
    '2011-03-20',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081512110048',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Asryanti',
    'Roni',
    'B'),
  ('5203084412040001',
    'Anggun Safitri',
    'Labuhan Lombok',
    '2004-12-04',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081512110048',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Sariah',
    'Saparudin',
    'O'),
  ('5203085507750013',
    'Sariah',
    'Labuhan Lombok',
    '1975-07-15',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203081512110048',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Mait',
    'Amaq Mait',
    'O'),
  ('5203083112720189',
    'Saparudin',
    'Labuhan Lombok',
    '1972-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Karyawan Swasta',
    'Indonesia',
    '5203081512110048',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '2000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Keramik',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Inaq Muhidin',
    'Amaq Muhidin',
    'O'),
  ('5203084901090002',
    'Mila',
    'Labuhan Lombok',
    '2009-01-09',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080906140022',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Sudiani',
    'Mahrip',
    'B'),
  ('5203085711950002',
    'Purnawati',
    'Grepek Sakra',
    '1995-11-17',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081601120026',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ini',
    'Amaq Ripaan',
    'O'),
  ('5203080107871733',
    'Zaenudin',
    'Labuhan Lombok',
    '1987-07-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081601120026',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Murni',
    'Amaq Kue Saman',
    'B'),
  ('5203085209180002',
    'Selfiana',
    'Pringgabaya',
    '2018-09-12',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081602100034',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Supiana Bt Daeng Hasan',
    'Fuad',
    'B'),
  ('5203084409150001',
    'Septiana',
    'Apitaik',
    '2015-09-04',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081602100034',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Supiana Bt Daeng Hasan',
    'Fuad',
    'A'),
  ('5203087112860300',
    'Supiana Bt Daeng Hasan',
    'Selong',
    '1986-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203081602100034',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hj. Atika',
    'Daeng Hasan',
    'B'),
  ('5203080107781191',
    'Fuad',
    'Apitaik',
    '1978-07-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh Nelayan',
    'Indonesia',
    '5203081602100034',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '108',
    '1',
    'Keramik',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hj. Imran',
    'H. M. Saefudin',
    'A'),
  ('5203084710980002',
    'Fitriana',
    'Labuhan Lombok',
    '1998-10-07',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203081602190001',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sabariah',
    'Rahimin',
    'O'),
  ('5203087011190003',
    'Novita Ardiyana',
    'Pringgabaya',
    '2019-11-30',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081602190001',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Fitriana',
    'Hardi Purna Irawan',
    'B'),
  ('5203084209160001',
    'Salma Nabila',
    'Labuhan Lombok',
    '2016-09-02',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081604120014',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Aminah',
    'Kurnaen',
    'O'),
  ('5203080810100005',
    'M. Zaki Ramadani',
    'Labuhan Lombok',
    '2010-10-08',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081604120014',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Aminah',
    'Kurnaen',
    'O'),
  ('5203084107781736',
    'Aminah',
    'Labuhan Lombok',
    '1978-07-01',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Pedagang',
    'Indonesia',
    '5203081604120014',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Radinah',
    'Amaq Muhali',
    'A'),
  ('5203082210110001',
    'Ikhsan Firdaus',
    'Labuhan Lombok',
    '2011-10-22',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081604120016',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sriana',
    'Hasanudin',
    'O'),
  ('5203083107060002',
    'Galih Ferdian',
    'Sambalia',
    '2006-07-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081604120016',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sriana',
    'Hasanudin',
    'B'),
  ('5203081212800018',
    'Hasanudin',
    'Sambalia',
    '1980-12-12',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081604120016',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Halimah',
    'Sanusi',
    'A'),
  ('5203080903130002',
    'Arya Wahyu Rahman',
    'Labuhan Lombok',
    '2013-03-09',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080901870001',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Tri Wahyu Retno. H',
    'Hardianto',
    'B'),
  ('5203085503900002',
    'Tri Wahyu Retno. H',
    'Pringgabaya',
    '1990-03-15',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080901870001',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nur Yolanda',
    'Mujiono',
    'B'),
  ('5203080901870001',
    'Hardianto',
    'Labuhan Lombok',
    '1987-01-09',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080901870001',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '50',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Numpang',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hasni',
    'Badran',
    'O'),
  ('5203085006630001',
    'Nur Yolanda',
    'Sidoarjo',
    '1963-06-10',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203085006630001',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '36',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Numpang',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Numpang',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ibu Suarni',
    'Mas Pri',
    'AB'),
  ('5203083112940126',
    'Wildan',
    'Labuhan Lombok',
    '1994-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Buruh Nelayan',
    'Indonesia',
    '5203081607120119',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Nur',
    'Amaq Nur',
    'A'),
  ('5203087112750352',
    'Inaq Nur',
    'Labuhan Lombok',
    '1975-12-31',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203081607120119',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '36',
    '1',
    'Keramik',
    'Bata',
    'Spandek',
    'Numpang',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Siti',
    'Amaq Siti',
    'B'),
  ('5203087107770005',
    'Rosdiati',
    'Batuyang',
    '1976-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203081609071630',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Musenip',
    'Nasri',
    'O'),
  ('5203081603690004',
    'Ahmad Muntasir',
    'Labuhan Lombok',
    '1969-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Karyawan Swasta',
    'Indonesia',
    '5203081609071630',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'S1/Sarjana',
    'Kepala Keluarga',
    '2000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Keramik',
    'Bata',
    'Genteng',
    'Sendiri',
    '300',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Hasnah',
    'Hasan Daeng Mari',
    'O'),
  ('5203081012990010',
    'Taufik',
    'Labuhan Lombok',
    '1996-06-02',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080807100066',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Halimah',
    'Nawawi',
    'B'),
  ('5203081011600005',
    'Nawawi',
    'Jantuk',
    '1960-11-10',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120054',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Cum',
    'Bapak Asan',
    'O'),
  ('5203086604850003',
    'Subaedah',
    'Labuhan Lombok',
    '1985-04-26',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081610130010',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Munasih',
    'Rahmat',
    'B'),
  ('5203082910750010',
    'Ahmad Fatoni S',
    'Labuhan Lombok',
    '1975-10-29',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081610130010',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hartia',
    'Kamarudin Sinuras',
    'A'),
  ('5203084612140003',
    'Inara Alifa Suja',
    'Labuhan Lombok',
    '2014-12-06',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081610140015',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Faurani',
    'Supardan',
    'O'),
  ('5203085905880002',
    'Faurani',
    'Gegurun',
    '1988-05-19',
    'Perempuan',
    'Islam',
    'Kawin',
    'Honorer',
    'Indonesia',
    '5203081610140015',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'S1/Sarjana',
    'Istri',
    '2000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Sihnun',
    'Mustajibuddin',
    'A'),
  ('5203080901850002',
    'Supardan',
    'Labuhan Lombok',
    '1985-01-09',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Honorer',
    'Indonesia',
    '5203081610140015',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'S1/Sarjana',
    'Famili Lain',
    '2000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Kusniah',
    'Zaenuddin',
    'B'),
  ('5203085910150003',
    'Jahira Anda Ana Maulida',
    'Selong',
    '2015-10-19',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081610200004',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rohyatun',
    'Junaedi',
    'O'),
  ('5203086503110007',
    'Maeda Indira',
    'Pringgabaya',
    '2011-03-25',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081610200004',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rohyatun',
    'Junaedi',
    'A')
on conflict (nik) do update set
  updated_at = now();
