-- ============================================================
-- SEED PART 73/79 — rows 7201–7300
-- Source: Tabel_Penduduk.csv
-- Idempotent: ON CONFLICT (nik) DO UPDATE SET updated_at = now()
-- ============================================================

insert into public.warga
  nik,
  nama,
  tempat_lahir,
  tanggal_lahir,
  jenis_kelamin,
  agama,
  status_perkawinan,
  pekerjaan,
  kewarganegaraan,
  no_kk,
  alamat,
  rt,
  rw,
  dusun,
  desa,
  kecamatan,
  kabupaten,
  provinsi,
  no_hp,
  pendidikan,
  status_dalam_kk,
  pendapatan_bulan,
  suku,
  kepemilikan_rumah,
  luas_rumah,
  jumlah_lantai,
  jenis_lantai,
  jenis_dinding,
  jenis_atap,
  kepemilikan_tanah,
  luas_tanah,
  penerangan,
  sumber_energi_masak,
  mck,
  sumber_air,
  bantuan_sosial,
  bantuan_extra,
  bpjs_kesehatan,
  bpjs_ketenagakerjaan,
  kepemilikan_aset,
  kondisi_fisik,
  nama_ibu,
  nama_bapak,
  golongan_darah
values
  ('5203080306940005',
    'Muhamad Saleh',
    'Labuhan Lombok',
    '1994-06-03',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082611150015',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Iq. Muhamad',
    'Amaq Muhamad',
    'B'),
  ('5203084301190003',
    'Mida Sandrina Putri',
    'Pringgabaya',
    '2019-01-03',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082611190007',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hernawati',
    'Saobil Zikri',
    'B'),
  ('5203085402990007',
    'Sisila Wati',
    'Menanga Baris',
    '1999-02-14',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082611190008',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Rianti',
    'Jenisah',
    'O'),
  ('5203087110190001',
    'Shaqila Oktavia',
    'Pringgabaya',
    '2019-10-31',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082611190008',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sisila Wati',
    'Kaharudin',
    'B'),
  ('5203084205020008',
    'Indah Sari',
    'Labuhan Lombok',
    '2002-05-12',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082611200011',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Muzayyadah',
    'Hang',
    'AB'),
  ('5203080107930005',
    'Lalu Rano',
    'Batman',
    '1993-07-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082611200011',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '50',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Numpang',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Baiq Fatimah',
    'Lalu Amin',
    'O'),
  ('5203081901210001',
    'Lalu M. Alfarizqi',
    'Selong',
    '2021-01-19',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082611200011',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Indah Sari',
    'Lalu Rano',
    'B'),
  ('5203080909030004',
    'Danu Saputra',
    'Labuhan Lombok',
    '2003-09-09',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082612110019',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurliana',
    'Lalu Supardi',
    'O'),
  ('5203081606000006',
    'Saipul Rahman',
    'Labuhan Lombok',
    '2000-07-16',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082612110019',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurliana',
    'Lalu Supardi',
    'O'),
  ('5203083010770001',
    'Lalu Supardi',
    'Labuhan Lombok',
    '1977-10-30',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082612110019',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Edok',
    'Mamiq Kemet',
    'A'),
  ('5203086505030003',
    'Mili Pratiwi',
    'Labuhan Lombok',
    '2003-05-25',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082612110021',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rumini',
    'Abdul Karim',
    'B'),
  ('5203086903160002',
    'Syafa Al Fida',
    'Selong',
    '2016-05-29',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082612110022',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurmayani',
    'Lutfi',
    'AB'),
  ('5203085211100003',
    'Zivilia Uswatul Hasanah',
    'Labuhan Lombok',
    '2010-11-12',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082612110022',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurmayani',
    'Lutfi',
    'A'),
  ('5203086811900001',
    'Nurmayani',
    'Labuhan Lombok',
    '1990-11-28',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082612110022',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rukiyah',
    'Sahnur',
    'O'),
  ('5203083008750001',
    'Lutfi',
    'Sulawesi',
    '1975-08-30',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082612110022',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hadera',
    'Saenuddin',
    'A'),
  ('5203086608120003',
    'Fitria Sifa''Ul Husna',
    'Labuhan Lombok',
    '2012-08-26',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082612120006',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhayati',
    'Sami''Un',
    'O'),
  ('5203080506040004',
    'Muhamad Aripin',
    'Labuhan Lombok',
    '2004-06-05',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082612120006',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhayati',
    'Sami''Un',
    'A'),
  ('5203087008730003',
    'Nurhayati',
    'Labuhan Lombok',
    '1973-08-30',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203082612120006',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Raimah',
    'Bp. Nurmah',
    'A'),
  ('5203081509700006',
    'Sami''Un',
    'Labuhan Lombok',
    '1970-09-15',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082612120006',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Saepul',
    'Amaq Saepul',
    'B'),
  ('5203080108190002',
    'Uwais Al- Qarni',
    'Selong',
    '2019-08-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082612120006',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhayati',
    'Sami''Un',
    'A'),
  ('5203084205760004',
    'Mardiana',
    'Labuhan Lombok',
    '1976-05-02',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082612120020',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Nurdin',
    'Amaq Nurdin',
    'O'),
  ('5203084804170004',
    'Atika Putri',
    'Pringgabaya',
    '2017-04-08',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120083',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Julina',
    'Anto',
    'O'),
  ('5203084405130004',
    'Yudi Azhari',
    'Pringgabaya',
    '2013-05-04',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120083',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Julina',
    'Anto',
    'O'),
  ('5203086402100001',
    'Widya Alika Pratiwi',
    'Pringgabaya',
    '2010-02-24',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120083',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Julina',
    'Anto',
    'B'),
  ('5203086107920002',
    'Julina',
    'Pringgabaya',
    '1992-07-21',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120083',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rohimah',
    'Syafrudin',
    'AB'),
  ('5203081504860005',
    'Anto',
    'Babana',
    '1986-04-15',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082701120083',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Syakka',
    'Syamsudin',
    'O'),
  ('5203080505190003',
    'Riski Jaya Rammadan',
    'Labuhan Lombok',
    '2019-05-05',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120083',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Julina',
    'Anto',
    'O'),
  ('5203085003120001',
    'Riski Wulandari',
    'Pringgabaya',
    '2012-03-10',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120086',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Warda',
    'Rusli',
    'A'),
  ('5203086103080003',
    'Risda Wahdana',
    'Balik Papan',
    '2008-03-21',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120086',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Warda',
    'Rusli',
    'B'),
  ('5203085003060006',
    'Lisda Mutiara',
    'Babana',
    '2006-03-10',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120086',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Warda',
    'Rusli',
    'O'),
  ('5203084707860004',
    'Warda',
    'Babana',
    '1986-07-07',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120086',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Syakka',
    'Syamsudin',
    'A'),
  ('5203080408810002',
    'Rusli',
    'Balik Papan',
    '1981-08-04',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082701120086',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Ibu Daud',
    'Daud',
    'O'),
  ('5203080206060003',
    'Pakih Ramdani',
    'Labuhan Lombok',
    '2006-06-02',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082701120101',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sumaiyah',
    'Taufan Azhari',
    'O'),
  ('5203081209830005',
    'Taufan Azhari',
    'Labuhan Lombok',
    '1983-09-12',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082701120101',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Saimah',
    'Ham''Makdah',
    'B'),
  ('5203084505800003',
    'Sumaiyah',
    'Sakra',
    '1980-05-05',
    'Perempuan',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082701120101',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Dizah',
    'Amaq Dizah',
    'B'),
  ('5203084405970004',
    'Herawati',
    'Pringgabaya',
    '1997-05-04',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082702190015',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Muliati',
    'Salihin',
    'A'),
  ('5203081303970002',
    'Muhammad Agus Maulidan',
    'Labuhan Lombok',
    '1995-08-03',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082702190015',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sabriah',
    'Barmawi',
    'O'),
  ('5203086308190002',
    'Laely Firzani',
    'Selong',
    '2019-08-23',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082702190015',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Herawati',
    'Muhammad Agus Maulidan',
    'A'),
  ('5203086308190003',
    'Laela Firzana',
    'Selong',
    '2019-08-23',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082702190015',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Herawati',
    'Muhammad Agus Maulidan',
    'A'),
  ('5203084404820003',
    'Rina Apriana',
    'Sikur',
    '1982-04-04',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082703120011',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Anemah',
    'Muhamad Sahab',
    'A'),
  ('5203087112750288',
    'Harni',
    'Apitaik',
    '1980-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203082703120011',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hajar',
    'Sabidi',
    'O'),
  ('5203081910170004',
    'Muhammad Zikril Akbar',
    'Pancor',
    '2017-10-19',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120036',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Husni Wati',
    'Samsudin',
    'A'),
  ('5203086111150002',
    'Revayanti',
    'Selong',
    '2015-11-21',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120036',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Husni Wati',
    'Samsudin',
    'B'),
  ('5203082610120005',
    'Muhamad Aidil Adha',
    'Pringgabaya',
    '2012-10-26',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120036',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Husni Wati',
    'Samsudin',
    'O'),
  ('5203080601080003',
    'Ilmi',
    'Labuhan Lombok',
    '2008-01-06',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120036',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Husni Wati',
    'Samsudin',
    'O'),
  ('5203086012030004',
    'Santi',
    'Labuhan Lombok',
    '2003-12-20',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082703120036',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Husni Wati',
    'Samsudin',
    'B'),
  ('5203080503950005',
    'Wardiman',
    'Sulteng',
    '1995-03-05',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203082703120036',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inak Samsul',
    'Sabir',
    'O'),
  ('5203083112800338',
    'Samsudin',
    'Sulteng',
    '1980-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082703120036',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Samsul',
    'Sabir',
    'B'),
  ('5203086606000006',
    'Ida Juniarti',
    'Labuhan Lombok',
    '2000-06-26',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120041',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mahtum',
    'Amaq Samsul Hadi',
    'O'),
  ('5203081909910005',
    'Ilham Suhardi',
    'Labuhan Lombok',
    '1991-09-19',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120041',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mahtum',
    'Amaq Samsul Hadi',
    'B'),
  ('5203085411650001',
    'Mahtum',
    'Batuyang',
    '1965-11-14',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Pedagang',
    'Indonesia',
    '5203082703120041',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Mahtum',
    'Papuq Mahtum',
    'B'),
  ('5203087112890223',
    'Saidah',
    'Lendang Jae Lembar',
    '1989-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203082703120048',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Min',
    'H. Abdurrahman',
    'O'),
  ('1705062212160001',
    'Arkaan Rizq Dhaifullah',
    'Bengkulu',
    '2016-12-22',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120051',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rosmeta Sari',
    'Azwandi',
    'B'),
  ('1705065606150001',
    'Aura Hafipa Azahra',
    'Bengkulu',
    '2015-06-16',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120051',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rosmeta Sari',
    'Azwandi',
    'A'),
  ('5203080405130003',
    'Ll. Muh. Rafli Hamzah',
    'Pringgabaya',
    '2013-05-04',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120051',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ridawati Rusli',
    'Lalu Suhaedi',
    'O'),
  ('5203086404090002',
    'Baiq Sulistiawati',
    'Labuhan Lombok',
    '2009-04-24',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703120051',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ridawati Rusli',
    'Lalu Suhaedi',
    'AB'),
  ('5203082205040004',
    'Lalu Heri Melsandi',
    'Labuhan Lombok',
    '2004-05-22',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082703120051',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ridawati Rusli',
    'Lalu Suhaedi',
    'A'),
  ('1705066302870001',
    'Rosmeta Sari',
    'Seluma',
    '1987-02-23',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082703120051',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Zulika',
    'Buyung Safri',
    'O'),
  ('5203084107822554',
    'Ridawati Rusli',
    'Labuhan Haji',
    '1982-07-01',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203082703120051',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rusnawati',
    'Bakri',
    'A'),
  ('5203080107801993',
    'Lalu Suhaedi',
    'Labuhan Lombok',
    '1980-07-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082703120051',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '300',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Isah',
    'Mamiq Mahruf',
    'B'),
  ('5203081402840006',
    'Hendra Wibowo',
    'Labuhan Lombok',
    '1984-02-14',
    'Laki-Laki',
    'Islam',
    'Cerai Hidup',
    'Wiraswasta',
    'Indonesia',
    '5203082703150006',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Daeng Hatijah',
    'Anto',
    'B'),
  ('5203085806170002',
    'Marwa Syaqila Azzahra',
    'Labuhan Lombok',
    '2017-06-18',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703170002',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nora Musdalipa',
    'Burhanuddin',
    'A'),
  ('5203085004990008',
    'Nora Musdalipa',
    'Labuhan Lombok',
    '1999-04-10',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082703170002',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Apsah',
    'Mustarip',
    'A'),
  ('7401200706810003',
    'Burhanuddin',
    'Tosiba',
    '1981-06-07',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082703170002',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Bua',
    'Uddin',
    'AB'),
  ('5203082305970004',
    'Bahtiar Aji',
    'Labuhan Lombok',
    '1997-05-25',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082704100002',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Tahlia',
    'Muhammad Nasiruddin',
    'O'),
  ('5203081810940001',
    'Rizal Idham',
    'Labuhan Lombok',
    '1994-10-18',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082704100002',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Tahlia',
    'M. Nasirudin',
    'A'),
  ('5205081209550001',
    'Ramli Pangaribuan',
    'Medan',
    '1955-09-12',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082704150001',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Tiodor',
    'Punngu',
    'O'),
  ('5203080301010003',
    'M. Alfin',
    'Labuhan Lombok',
    '2001-01-03',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203082704210008',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sumiati',
    'Harun',
    'O'),
  ('5202086607940001',
    'Nurul Hidayani',
    'Karang Jangkong',
    '1994-07-26',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082704210008',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'S1/Sarjana',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhaini',
    'Irsat',
    'AB'),
  ('5203082206200008',
    'Yusuf Abdullah',
    'Peresak',
    '2020-06-22',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082704210008',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurul Hidayani',
    'M. Alfin',
    'B'),
  ('5203080812170005',
    'Andi Bariq Maulana',
    'Labuhan Lombok',
    '2017-09-08',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082705190004',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rofi Yatul Khotijah',
    'Daeng Sugi Purwanto',
    'O'),
  ('5203081101130002',
    'Andi Bara Maulana Azhar',
    'Labuhan Lombok',
    '2013-01-11',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082705190004',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rofi Yatul Khotijah',
    'Daeng Sugi Purwanto',
    'O'),
  ('3510165506110002',
    'Nadia Melati Purnama',
    'Banyuwangi',
    '2011-06-15',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082705190004',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rofi Yatul Khotijah',
    'Sugi Purwanto',
    'B'),
  ('5203084508880006',
    'Rofi Yatul Khotijah',
    'Banyuwangi',
    '1988-08-05',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082705190004',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Insian',
    'Mansyur',
    'B'),
  ('3510161705840005',
    'Sugi Purwanto',
    'Banyuwangi',
    '1984-05-17',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082705190004',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Samiah',
    'Peta Bolek',
    'B'),
  ('5203086706120003',
    'Zilfi Andriyani',
    'Labuhan Lombok',
    '2012-06-27',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082706120012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Heriani',
    'Andri Pratama',
    'A'),
  ('5203086404910004',
    'Heriani',
    'Labuhan Lombok',
    '1991-04-24',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082706120012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sahra',
    'M. Nasir',
    'A'),
  ('5203080212900002',
    'Andri Pratama',
    'Labuhan Lombok',
    '1990-12-02',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082706120012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Kelsum',
    'Lukman',
    'A'),
  ('5203086207190005',
    'Adila Nisa Indriyani',
    'Pringgabaya',
    '2019-07-22',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082706120012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Heriani',
    'Andri Pratama',
    'O'),
  ('5203081905050008',
    'Ramdani',
    'Bengkel',
    '2005-05-19',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082706120026',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhasanah',
    'Daeng Hasan',
    'A'),
  ('5203087112660120',
    'Masiah',
    'Labuhan Lombok',
    '1966-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203082706120038',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurjanah',
    'Radiah',
    'AB'),
  ('5203083112620206',
    'Muhammad Amin',
    'Jantuk',
    '1962-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Transportasi/Ojek/Supir',
    'Indonesia',
    '5203082706120038',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sanaria',
    'Amir',
    'A'),
  ('5203083112350022',
    'Wa'' Maini',
    'Kopang',
    '1935-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082706120043',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '24',
    '1',
    'Semen',
    'Papan',
    'Spandek',
    'Numpang',
    '0',
    'Non PLN',
    'Kayu Bakar',
    'Numpang',
    'Mata Air',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Hindong',
    'Kasimah',
    'B'),
  ('5203081212750017',
    'Muslimin',
    'Bima',
    '1975-12-12',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082706160004',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Genung',
    'Waq Janji',
    'B'),
  ('5203087112600342',
    'Hasia',
    'Labuhan Lombok',
    '1948-12-31',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203082706180004',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Numpang',
    '24',
    '1',
    'Semen',
    'Papan',
    'Spandek',
    'Numpang',
    '0',
    'Non PLN',
    'Kayu Bakar',
    'Numpang',
    'Mata Air',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Jumahir',
    'Wak Mariam',
    'AB'),
  ('5203084301960004',
    'Fitriah',
    'Labuhan Lombok',
    '1996-01-03',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082706180006',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Famili Lain',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Bedah',
    'Kasidah',
    'B'),
  ('5203080508160003',
    'Dzaky Alma''Ir Jamil',
    'Pringgabaya',
    '2016-08-05',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082707150001',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Erna Wati',
    'Muhammad Iksan',
    'O'),
  ('5203081209190004',
    'Rio Andriansyah',
    'Pringgabaya',
    '2019-09-12',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082707150012',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Juliati',
    'Andika Pirmansyah',
    'O'),
  ('5203084109060010',
    'Aura Aulia Ramadani',
    'Labuhan Lombok',
    '2006-09-01',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082708120072',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Laela Ani Harman',
    'Ardianto',
    'B'),
  ('5203086102890003',
    'Laela Ani Harman',
    'Labuhan Lombok',
    '1989-02-21',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203082708120072',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Halimah',
    'Suparman',
    'O'),
  ('5203081804820002',
    'Ardianto',
    'Labuhan Mapin',
    '1982-04-18',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082708120072',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Nurlaela',
    'Abd. Rasyid',
    'B'),
  ('5203080210070002',
    'Jihad Akbar',
    'Labuhan Lombok',
    '2007-10-02',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082708140001',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sumiati',
    'Junaidi',
    'A'),
  ('5203082711150002',
    'Ayaz Fahlefi Ahmad',
    'Pancor',
    '2015-11-27',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082709140014',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Diana Lestari',
    'Edwin Andri',
    'B'),
  ('5203086006920012',
    'Diana Lestari',
    'Labuhan Lombok',
    '1992-06-20',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tenaga Kesehatan',
    'Indonesia',
    '5203082709140014',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'Diploma',
    'Istri',
    '2000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Satariah',
    'Ali',
    'O'),
  ('5203081512880003',
    'Edwin Andri',
    'Labuhan Lombok',
    '1988-12-15',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Guru/Pendidik',
    'Indonesia',
    '5203082709140014',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'S1/Sarjana',
    'Kepala Keluarga',
    '2000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Bata',
    'Genteng',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Ya',
    'Ya',
    'Roda 2',
    'Normal',
    'Rohani',
    'Junaidi,s.pd',
    'B'),
  ('5203085501210001',
    'Aina Syafara Dwiana',
    'Selong',
    '2021-01-15',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082709140014',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Diana Lestari',
    'Edwin Andri',
    'B'),
  ('5203080911920006',
    'Heri Budi Hartono',
    'Kedindi',
    '1992-11-09',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Petani',
    'Indonesia',
    '5203082710140003',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rohimin',
    'Mahyun',
    'A'),
  ('5203086010710004',
    'Rohimin',
    'Pringgabaya',
    '1971-10-20',
    'Perempuan',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203082710140003',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Rohimin',
    'Amaq Rohimin',
    'B'),
  ('5203081010700008',
    'Mahyun',
    'Dusun Mandar',
    '1970-10-10',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203082710140003',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Kembi',
    'Amaq Suhaili',
    'B'),
  ('5203085512770006',
    'Mahnim',
    'Gelanggang',
    '1977-12-15',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Wiraswasta',
    'Indonesia',
    '5203082710140031',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Rianah',
    'Sinarah',
    'O')
on conflict (nik) do update set
  updated_at = now();
