-- ============================================================
-- SEED PART 1/79 — rows 1–100
-- Source: Tabel_Penduduk.csv
-- Idempotent: ON CONFLICT (nik) DO UPDATE SET updated_at = now()
-- ============================================================

insert into public.warga
  nik,
  nama,
  tempat_lahir,
  tanggal_lahir,
  jenis_kelamin,
  agama,
  status_perkawinan,
  pekerjaan,
  kewarganegaraan,
  no_kk,
  alamat,
  rt,
  rw,
  dusun,
  desa,
  kecamatan,
  kabupaten,
  provinsi,
  no_hp,
  pendidikan,
  status_dalam_kk,
  pendapatan_bulan,
  suku,
  kepemilikan_rumah,
  luas_rumah,
  jumlah_lantai,
  jenis_lantai,
  jenis_dinding,
  jenis_atap,
  kepemilikan_tanah,
  luas_tanah,
  penerangan,
  sumber_energi_masak,
  mck,
  sumber_air,
  bantuan_sosial,
  bantuan_extra,
  bpjs_kesehatan,
  bpjs_ketenagakerjaan,
  kepemilikan_aset,
  kondisi_fisik,
  nama_ibu,
  nama_bapak,
  golongan_darah
values
  ('5203035003120001',
    'Wiwik Ariani Sapura',
    'Praubanyar',
    '2012-03-10',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203032809120020',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Kartini',
    'Saparudin',
    'A'),
  ('5203030408100004',
    'Muhamad Taupan Saputra',
    'Terara',
    '2010-08-04',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203032809120020',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Kartini',
    'Saparudin',
    'O'),
  ('5203034107740482',
    'Kartini',
    'Sukadana',
    '1974-07-01',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Pedagang',
    'Indonesia',
    '5203032809120020',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '108',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '400',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Muhamad',
    'Amaq Muhamad',
    'O'),
  ('5203082003170003',
    'Edgar Atala Nando',
    'Pringgabaya',
    '2017-03-20',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080102160004',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nanda Ayu Riska Ismiardi',
    'Abdul Muis',
    'B'),
  ('5203085405140001',
    'Elfariza Haura Ataya',
    'Mataram',
    '2014-05-14',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080102160004',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nanda Ayu Riska Ismiardi',
    'Abdul Muis',
    'A'),
  ('5203083010900005',
    'Abdul Muis',
    'Labuhan Lombok',
    '1992-04-12',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080102160004',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Keramik',
    'Bata',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sopiah Hasan',
    'Syarafuddin',
    'A'),
  ('5203080201210001',
    'Ersya Samudra',
    'Selong',
    '2021-01-02',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080102160004',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nanda Ayu Riska Ismiardi',
    'Abdul Muis',
    'O'),
  ('5203082002090001',
    'M. Fajar Al Irsyad',
    'Rote',
    '2009-02-20',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080102170001',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Indrawati',
    'M. Ali Ramdani',
    'B'),
  ('5203085303870001',
    'Indrawati',
    'Labuhan Lombok',
    '1987-03-13',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Pedagang',
    'Indonesia',
    '5203080102170001',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Keramik',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sakmah',
    'Sayuti',
    'B'),
  ('5203087112700268',
    'Sahura',
    'Labuhan Lombok',
    '1970-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203082802120015',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Siti Naimah',
    'Daeng Sumang',
    'B'),
  ('5203083112680163',
    'Abd. Aziz',
    'Makaranganan',
    '1968-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082802120015',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Badi''A',
    'Daeng Taming',
    'O'),
  ('5203081801110001',
    'Didi Samsul Hadi',
    'Labuhan Lombok',
    '2011-01-18',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080103120017',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hayani',
    'M. Amin',
    'A'),
  ('5203086412030002',
    'Ema Salmiani',
    'Labuhan Lombok',
    '2003-12-24',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pedagang',
    'Indonesia',
    '5203080103120017',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hayani',
    'M. Amin',
    'B'),
  ('5203084601790003',
    'Hayani',
    'Labuhan Lombok',
    '1979-01-06',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080103120017',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Setiara',
    'Wak Sukur',
    'O'),
  ('5203080511700002',
    'M. Amin',
    'Masbagik',
    '1970-11-05',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080103120017',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Papan',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Mahyum',
    'Amaq Maksun',
    'B'),
  ('5203083112640118',
    'Daeng Jabir',
    'Sinjai',
    '1964-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080103120041',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Mariana',
    'H.Latip',
    'A'),
  ('5203084104040010',
    'Afriani',
    'Labuhan Lombok',
    '2004-04-01',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080103180013',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sumiati',
    'Junaedi',
    'AB'),
  ('5203083112790464',
    'Ahmad Junaedi Aksa',
    'Labuhan Lombok',
    '1979-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080907100018',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhayati',
    'Muhammad Aksa',
    'A'),
  ('5203080708170002',
    'M. Gandi Gunawan',
    'Labuhan Lombok',
    '2017-08-07',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080106150049',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mildawati',
    'Hendra Gunawan',
    'O'),
  ('5203083112930197',
    'Hendra Gunawan',
    'Labuhan Lombok',
    '1993-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081109120082',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Fatmawati',
    'Yakub',
    'AB'),
  ('5203084707890006',
    'Mildawati',
    'Labuhan Lombok',
    '1989-07-07',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080106150049',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hikmah',
    'Kamil',
    'B'),
  ('5203084701210001',
    'Mila Annasya Gunawan',
    'Pringgabaya',
    '2021-01-07',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080106150049',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mildawati',
    'Hendra Gunawan',
    'A'),
  ('5203081403780001',
    'Satriadi',
    'Labuhan Lombok',
    '1978-03-14',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203080107130007',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Habariah',
    'Aliman',
    'O'),
  ('5203086904020003',
    'Firda Apriana',
    'Labuhan Lombok',
    '2002-04-29',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081109120039',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rahmi',
    'Pua Ismail',
    'A'),
  ('5203081606140006',
    'Diego Junian Jayadi',
    'Pringgabaya',
    '2014-06-16',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080308210004',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurhayati',
    'Herman Jayadi',
    'O'),
  ('5203086008130005',
    'Aswatun Nisa',
    'Pringgabaya',
    '2013-08-20',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081311120086',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    'Sendiri',
    '24',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Numpang',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Ismawati',
    'Suparlan',
    'B'),
  ('5203085506970004',
    'Rosdiana',
    'Labuhan Lombok',
    '1997-06-15',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080211150012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hae Ah',
    'Aminullah Ahmad',
    'A'),
  ('5203085906930001',
    'Supiana',
    'Labuhan Lombok',
    '1993-06-19',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080211150012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hae Ah',
    'Aminullah Ahmad',
    'O'),
  ('5203083012890008',
    'Ahmad Akbar',
    'Labuhan Lombok',
    '1989-12-30',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203080211150012',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '50',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hae Ah',
    'Aminullah Ahmad',
    'A'),
  ('5203083112780316',
    'Syahrudin',
    'Ampenan',
    '1978-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080110120033',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Masitah',
    'Srinah',
    'B'),
  ('5203084107731402',
    'Nahadiah',
    'Labuhan Lombok',
    '1973-07-01',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080110120033',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Pujiah',
    'Simail',
    'O'),
  ('5203080808830004',
    'Nashrudin',
    'Labuhan Lombok',
    '1983-08-08',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080111120100',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sukaena',
    'Syahrum',
    'B'),
  ('5203082905050002',
    'M. Ikbal',
    'Labuhan Lombok',
    '2005-05-29',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '520308011020OOO5',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nurmawati',
    'Pang Japar',
    'O'),
  ('5203080105990005',
    'Jepri Normasyah',
    'Labuhan Lombok',
    '1999-05-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '520308011020OOO5',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '50',
    '1',
    'Keramik',
    'Bata',
    'Genteng',
    'Sendiri',
    '300',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Nurmawati',
    'Pang Japar',
    'O'),
  ('5203083112720416',
    'Nurdin',
    'Labuhan Lombok',
    '1972-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh',
    'Indonesia',
    '5203080111120016',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Siti',
    'Pakoerijah',
    'B'),
  ('5203087112520124',
    'Buniah',
    'Sakra',
    '1944-12-31',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120024',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Sendiri',
    '24',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Numpang',
    '300',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Buniah',
    'Amaq Bedah',
    'A'),
  ('5203085112870012',
    'Khulutiyah',
    'Gegurun',
    '1987-12-11',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080111120039',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Sahyum',
    'Amaq Sahyum',
    'O'),
  ('5203083101860003',
    'Alimudin',
    'Labuhan Lombok',
    '1986-01-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh Nelayan',
    'Indonesia',
    '5203080111120039',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Dames',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Keramik',
    'Bata',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Bq. Sinah',
    'Ll. Maini',
    'A'),
  ('5203087112710211',
    'Nahariya',
    'Labuhan Lombok',
    '1971-12-31',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120045',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Sendiri',
    '30',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Numpang',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Masirah',
    'M. Said',
    'O'),
  ('5203080311120001',
    'Muhammad Shopi Anwar Khairi',
    'Pringgabaya',
    '2012-11-03',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111200503',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Jumraini',
    'Ahmad Januri',
    'A'),
  ('5203085503080004',
    'Nurul Alivia',
    'Labuhan Lombok',
    '2008-03-15',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111200503',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Jumraini',
    'Ahmad Januri',
    'A'),
  ('5203087103880001',
    'Jumraini',
    'Labuhan Lombok',
    '1988-03-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080111200503',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Siti Aisyah',
    'Amaq As',
    'A'),
  ('5203084805190004',
    'Loja Shovia Ahmad',
    'Pringgabaya',
    '2019-05-08',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111200503',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Jumraini',
    'Ahmad Januri',
    'B'),
  ('5203083112720417',
    'Ahmad Laduni',
    'Jantuk',
    '1972-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080111120052',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Siti Hajar',
    'Nawawi',
    'A'),
  ('5203084311720001',
    'Pidyatun',
    'Jantuk',
    '1972-11-03',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080111120052',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Mena',
    'Ishak',
    'B'),
  ('5203083112860435',
    'Amirullah',
    'Labuhan Lombok',
    '1986-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080907100015',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Aminah',
    'Durahman',
    'A'),
  ('5203081505120003',
    'Aisar',
    'Bandok',
    '2012-05-15',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120058',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Wahyuni',
    'Ahmadi',
    'B'),
  ('5203086008930002',
    'Wahyuni',
    'Tembeng Putek',
    '1993-08-20',
    'Perempuan',
    'Islam',
    'Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120058',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sahnim',
    'Dinah',
    'A'),
  ('5203080309740002',
    'Ahmadi',
    'Bone',
    '1974-09-03',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080111120058',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '102',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hj. Salawati',
    'H. Haseng',
    'A'),
  ('5203081203070008',
    'Ferdian Isrori',
    'Labuhan Lombok',
    '2007-03-12',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120061',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Bq. Kurniah',
    'Basarudin',
    'A'),
  ('5203081303050006',
    'Ramzi Fathurahman',
    'Labuhan Lombok',
    '2005-03-13',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120061',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Bq. Kurniah',
    'Basarudin',
    'B'),
  ('5203080107671861',
    'Basarudin',
    'Labuhan Lombok',
    '1967-07-01',
    'Laki-Laki',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120061',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Sendiri',
    '150',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Numpang',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tunadaksa',
    'Jaenah',
    'Samiun',
    'A'),
  ('5203080107891886',
    'Saparwadi',
    'Labuhan Lombok',
    '1989-07-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120068',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tunadaksa',
    'Bedah',
    'Kasidah',
    'A'),
  ('5203087112600483',
    'Bedah',
    'Labuhan Lombok',
    '1946-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203080111120068',
    'Jln. Raya Sambelia',
    '006',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1500000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Udin',
    'Amaq Udin',
    'A'),
  ('5203082310620002',
    'Habibuddin',
    'Mamben',
    '1962-10-23',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080111120079',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Siti Hadijah',
    'H. Abdul Mannan',
    'O'),
  ('5203080203970002',
    'Irwansyah',
    'Labuhan Lombok',
    '1997-03-02',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080111120097',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Quratul Am',
    'Supardi',
    'B'),
  ('5203083112740371',
    'Supardi',
    'Kediri',
    '1974-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080111120097',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1500000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Asbes',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hj. Saadah',
    'H. Sayuti',
    'O'),
  ('5203081710100005',
    'Ismail Farukh Elrazi. A',
    'Labuhan Lombok',
    '2010-10-17',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082508100017',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Elmiyati',
    'Abdul Halim. A',
    'B'),
  ('5203081111040011',
    'Abd. Fathir Zaidhan Ahmad',
    'Labuhan Lombok',
    '2004-11-11',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082508100017',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Elmiyati',
    'Abdul Halim. A',
    'B'),
  ('5203080911800002',
    'Abdul Halim. A',
    'Labuhan Lombok',
    '1980-11-09',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203082508100017',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Fatmah',
    'Ahmad Ws',
    'O'),
  ('5203080108720006',
    'Hatman',
    'Jantuk',
    '1972-08-01',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080111120100',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Sakmah',
    'Abdul Hamid',
    'O'),
  ('5203080107120023',
    'Ahmad Khalqi',
    'Pringgabaya',
    '2012-07-01',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203081204120035',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rohatun',
    'Suhardi',
    'A'),
  ('5203087007040010',
    'Zaulanan Nadia',
    'Labuhan Lombok',
    '2004-07-30',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203081204120035',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rohatun',
    'Suhardi',
    'B'),
  ('5203083112850453',
    'Suhardi',
    'Labuhan Lombok',
    '1985-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203081204120035',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sadrah',
    'Riwansyah',
    'O'),
  ('5203081505720005',
    'Moh.amin',
    'Labuhan Lombok',
    '1972-05-15',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203086411650001',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Munasih',
    'Abdullah',
    'O'),
  ('5203085001710001',
    'Baiq Nurjannah',
    'Labuhan Lombok',
    '1971-01-10',
    'Perempuan',
    'Islam',
    'Kawin',
    'Wiraswasta',
    'Indonesia',
    '5203086411650001',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Jaweriah',
    'L.moh.sapoan Z',
    'B'),
  ('5203081402960007',
    'Zulkifli',
    'Labuhan Lombok',
    '1996-02-17',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203082102180009',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Amenah',
    'Lalu Bukri',
    'O'),
  ('5203081103170001',
    'Al Ardahikam Marna',
    'Selong',
    '2017-03-11',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130019',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Erna Yunita',
    'Rizal Marsudi',
    'O'),
  ('5203082002120005',
    'Abd. Halim Haikal Marna',
    'Labuhan Lombok',
    '2012-02-20',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130019',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Erna Yunita',
    'Rizal Marsudi',
    'B'),
  ('5203083004900004',
    'Rizal Marsudi',
    'Labuhan Lombok',
    '1990-04-30',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh Nelayan',
    'Indonesia',
    '5203080201130019',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1200000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Mantasia',
    'Muktar',
    'A'),
  ('5203087112450147',
    'Mustiarep',
    'Masbagik',
    '1945-12-31',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080201130028',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Martawang',
    'Mamiq Martawang',
    'O'),
  ('5203083112430060',
    'Marlin',
    'Labuhan Lombok',
    '1943-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203080201130028',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '150',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Lembain',
    'Tinah',
    'O'),
  ('5203081209990008',
    'Andri Ferianto',
    'Labuhan Lombok',
    '1999-12-15',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203080209210010',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Hayati',
    'Sarudin',
    'B'),
  ('5203087112720433',
    'Maiyah',
    'Sakra',
    '1972-12-31',
    'Perempuan',
    'Islam',
    'Cerai Hidup',
    'Pedagang',
    'Indonesia',
    '5203080201130038',
    'Jln. Raya Sambelia',
    '004',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Isah',
    'Amaq Isah',
    'B'),
  ('5203082306150001',
    'Muhamad Ramdani',
    'Labuhan Lombok',
    '2015-06-23',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130039',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hudusiah',
    'Zaenul Hidayat',
    'O'),
  ('5203080403120002',
    'Ahmad Jumirza',
    'Apitaik',
    '2012-03-04',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130039',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Hudusiah',
    'Zaenul Hidayat',
    'O'),
  ('5203084204890002',
    'Hudusiah',
    'Apitaik',
    '1989-04-02',
    'Perempuan',
    'Islam',
    'Kawin',
    'Pedagang',
    'Indonesia',
    '5203080201130039',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'I. Sa''Diah',
    'A. Hubudiah',
    'B'),
  ('5203082804800003',
    'Zaenul Hidayat',
    'Labuhan Lombok',
    '1980-04-28',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Nelayan',
    'Indonesia',
    '5203080201130039',
    'Jln. Raya Sambelia',
    '002',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'I. Zuhaeriah',
    'A. Mulyadi',
    'A'),
  ('5203083112950177',
    'Herman Wirahadi',
    'Labuhan Lombok',
    '1995-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh',
    'Indonesia',
    '5203080201130058',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Famili Lain',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Senah',
    'M. Nasir',
    'O'),
  ('5203087012450006',
    'Senah',
    'Labuhan Lombok',
    '1945-12-30',
    'Perempuan',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203080201130058',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Subaiyah',
    'Amaq Slimah',
    'A'),
  ('5203083112420088',
    'M. Nasir',
    'Labuhan Lombok',
    '1942-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203080201130058',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Nasir',
    'Amaq Nasir',
    'O'),
  ('5203082305950002',
    'Andi Edi Mariadi',
    'Labuhan Lombok',
    '1995-05-23',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203080201130063',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Suburiah',
    'Arden',
    'A'),
  ('5203080502140001',
    'Galang Maulana Najar',
    'Labuhan Lombok',
    '2014-02-05',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130069',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Siti Hajar',
    'Nasrudin',
    'O'),
  ('5203083112080029',
    'Agus Galuh Saputra',
    'Masbagik',
    '2008-12-31',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130069',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Siti Hajar',
    'Nasrudin',
    'B'),
  ('5203087012860006',
    'Siti Hajar',
    'Mamben',
    '1986-12-30',
    'Perempuan',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203080201130069',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Inaq Suniah',
    'Amaq Suniah',
    'B'),
  ('5203083112720459',
    'Nasrudin',
    'Labuhan Lombok',
    '1972-12-31',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Petani',
    'Indonesia',
    '5203080201130069',
    'Jln. Raya Sambelia',
    '005',
    NULL,
    'Brangtapen Asri',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Semen',
    'Batako',
    'Spandek',
    'Sendiri',
    '100',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'Perpipaan',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Inaq Misrah',
    'Amaq Misrah',
    'O'),
  ('5203081206110004',
    'Muhammad Yusril',
    'Labuhan Lombok',
    '2000-06-07',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082910120143',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Fatmiati',
    'Kaharuddin Syah',
    'B'),
  ('5203081803990001',
    'Muhammad Ali Fikri',
    'Labuhan Lombok',
    '1999-03-18',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082910120143',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Fatmiati',
    'Kaharuddin Syah',
    'A'),
  ('5203081006740002',
    'Kaharuddin Syah',
    'Labuhan Lombok',
    '1974-06-10',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082910120143',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Hasuna',
    'Abu Hakim',
    'B'),
  ('5203085708730005',
    'Fatmiati',
    'Alas',
    '1973-08-17',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082910120143',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Ya',
    'Tidak',
    'Tidak',
    'Normal',
    'Masitah',
    'Mustaip',
    'B'),
  ('5203082412970004',
    'Shandy Rizky Pratama',
    'Labuhan Lombok',
    '1997-12-24',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Nelayan',
    'Indonesia',
    '5203080201130077',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '1000000',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Sohra',
    'Moh. Said',
    'O'),
  ('5203087112520151',
    'Mukminah',
    'Labuhan Lombok',
    '1952-12-31',
    'Perempuan',
    'Islam',
    'Cerai Mati',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130077',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Mandar',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Kepala Keluarga',
    '0',
    'Sasak',
    'Sendiri',
    '198',
    '1',
    'Semen',
    'Bata',
    'Spandek',
    'Numpang',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Ya',
    'Ya',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Saleha',
    'Nyantel',
    'O'),
  ('5203085503170003',
    'Alia Saputri',
    'Pringgabaya',
    '2017-03-15',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Pelajar/Mahasiswa',
    'Indonesia',
    '5203082501120058',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rudiah',
    'Jumadil',
    'B'),
  ('5203081409070001',
    'Rian Sanjaya',
    'Labuhan Lombok',
    '2007-09-14',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082501120058',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rudiah',
    'Jumadil',
    'O'),
  ('5203087112870411',
    'Rudiah',
    'Labuhan Lombok',
    '1987-12-31',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203082501120058',
    'Jln. Raya Sambelia',
    '003',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SD/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Naimah',
    'Agus Salim',
    'O'),
  ('5203081312080003',
    'Lalu Teguh Barata',
    'Labuhan Lombok',
    '2008-12-13',
    'Laki-Laki',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130084',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Nur''Aeni',
    'Lalu Agus Satriawan',
    'O'),
  ('5203081610800001',
    'Lalu Agus Satriawan',
    'Labuhan Lombok',
    '1980-10-16',
    'Laki-Laki',
    'Islam',
    'Kawin',
    'Buruh Nelayan',
    'Indonesia',
    '5203080201130084',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMA/Sederajat',
    'Kepala Keluarga',
    '1000000',
    'Sasak',
    'Sendiri',
    '48',
    '1',
    'Keramik',
    'Bata',
    'Genteng',
    'Sendiri',
    '200',
    'PLN',
    'Gas LPG 3 Kg',
    'Sendiri',
    'PDAM',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Roda 2',
    'Normal',
    'Subaedah',
    'Lalu Burhanudin',
    'B'),
  ('5202124107800319',
    'Mianah',
    'Lantan Duren',
    '1980-07-01',
    'Perempuan',
    'Islam',
    'Kawin',
    'Ibu Rumah Tangga',
    'Indonesia',
    '5203080201130084',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Istri',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Rinayi',
    'Srianom',
    'A'),
  ('5203086907200005',
    'Bq.citraarasely Satriawan',
    'Desa Lantan',
    '2020-07-29',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130084',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'PAUD',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Mianah',
    'Lalu Agus Satriawan',
    'A'),
  ('5203086111100006',
    'Novita',
    'Labuhan Lombok',
    '2010-11-21',
    'Perempuan',
    'Islam',
    'Belum Kawin',
    'Tidak Bekerja',
    'Indonesia',
    '5203080201130086',
    'Jln. Raya Sambelia',
    '001',
    NULL,
    'Sasak',
    'Seruni Mumbul',
    'Pringgabaya',
    'Lombok Timur',
    'Nusa Tenggara Barat',
    NULL,
    'SMP/Sederajat',
    'Anak',
    '0',
    'Sasak',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    '-',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Tidak',
    'Normal',
    'Turi',
    'Safa''At',
    'O')
on conflict (nik) do update set
  updated_at = now();
