-- Seed Data for surat_template from SURAT_MASTER
-- This script populates the surat_template table with 73 letter types.

TRUNCATE public.surat_template;

INSERT INTO public.surat_template (code, name, category, description, eta, syarat, fields, status)
VALUES 
('SKD', 'Surat Keterangan Domisili', 'Kependudukan', 'Surat paling fundamental dan paling banyak dipakai. Wewenang penuh desa. Semua keperluan domisili.', '1 hari kerja', '["Fotokopi KTP", "Fotokopi Kartu Keluarga", "Surat pengantar RT/RW"]', '[{"key": "keperluan", "label": "Keperluan", "type": "textarea", "placeholder": "Contoh: Untuk persyaratan pembukaan rekening bank...", "required": true, "colSpan": 2}, {"key": "lama_tinggal", "label": "Lama Berdomisili", "type": "text", "placeholder": "Contoh: 5 tahun", "required": true}]', 'Disetujui'),
('PINDAH_DOMISILI', 'Surat Keterangan Pindah Domisili', 'Kependudukan', 'Wewenang desa. Syarat mutasi kepindahan di Dukcapil dengan form F-1.02.', '2 hari kerja', '["Fotokopi KTP & KK", "Form F-1.02 dari Dukcapil", "Surat pengantar RT/RW"]', '[{"key": "alamat_tujuan", "label": "Alamat Tujuan", "type": "textarea", "required": true, "colSpan": 2}, {"key": "alasan_pindah", "label": "Alasan Pindah", "type": "select", "options": ["Pekerjaan", "Pendidikan", "Keluarga", "Keamanan", "Lainnya"], "required": true}, {"key": "jumlah_pengikut", "label": "Jumlah Anggota Keluarga yang Pindah", "type": "number", "required": true}, {"key": "jenis_kepindahan", "label": "Jenis Kepindahan", "type": "select", "options": ["Kepindahan dalam satu desa/kelurahan", "Kepindahan antar desa/kelurahan", "Kepindahan antar kecamatan", "Kepindahan antar kabupaten/kota", "Kepindahan antar provinsi"], "required": true}]', 'Disetujui'),
('PENDATANG', 'Surat Keterangan Pendatang / Numpang KK', 'Kependudukan', 'Wewenang desa. Catat pendatang yang numpang KK. Syarat KK baru.', '1 hari kerja', '["Fotokopi KTP pendatang", "KK baru pemilik", "Surat pengantar RT/RW"]', '[{"key": "asal", "label": "Asal Pendatang (Desa/Kecamatan/Kabupaten)", "type": "text", "required": true}, {"key": "alasan_datang", "label": "Alasan Datang", "type": "select", "options": ["Kerja", "Kunjungan", "Menetap", "Lainnya"], "required": true}, {"key": "lama_tinggal", "label": "Lama Tinggal (hari/bulan)", "type": "text", "required": true}, {"key": "nama_pemilik_kk", "label": "Nama Pemilik KK yang Ditumpangi", "type": "text", "required": true}]', 'Disetujui'),
('KK_BARU', 'Surat Keterangan Kepala Keluarga', 'Kependudukan', 'Akses program bantuan (PKH, BST). Untuk warga yang belum punya KK.', '2 hari kerja', '["Fotokopi KTP semua anggota", "Surat pengantar RT/RW", "Keterangan hilang dari kepolisian (jika hilang)"]', '[{"key": "alasan", "label": "Alasan Belum Punya KK", "type": "select", "options": ["KK hilang", "Belum terbit", "Pisah KK", "Lainnya"], "required": true}, {"key": "jumlah_anggota", "label": "Jumlah Anggota Keluarga", "type": "number", "required": true}, {"key": "daftar_anggota", "label": "Daftar Anggota Keluarga", "type": "textarea", "helper": "Nama, NIK, hubungan keluarga", "required": true, "colSpan": 2}]', 'Disetujui'),
('BEDA_NAMA', 'Surat Keterangan Beda Nama', 'Kependudukan', 'Penyamaan 2 nama berbeda di 2 dokumen.', '1 hari kerja', '["Fotokopi kedua dokumen", "Fotokopi KTP & KK", "Surat pengantar RT/RW"]', '[{"key": "dokumen1", "label": "Nama di Dokumen 1", "type": "text", "required": true}, {"key": "keperluan", "label": "Keperluan", "type": "textarea", "placeholder": "Jelaskan keperluan pengajuan surat ini...", "required": true, "colSpan": 2}, {"key": "jenis_dokumen1", "label": "Jenis Dokumen 1", "type": "select", "options": ["KTP", "KK", "Ijazah", "Akta Kelahiran", "Buku Nikah"], "required": true}, {"key": "dokumen2", "label": "Nama di Dokumen 2", "type": "text", "required": true}, {"key": "jenis_dokumen2", "label": "Jenis Dokumen 2", "type": "select", "options": ["KTP", "KK", "Ijazah", "Akta Kelahiran", "Buku Nikah"], "required": true}]', 'Disetujui'),
('ALAMAT_SEMENTARA', 'Surat Keterangan Alamat Sementara', 'Kependudukan', 'Untuk warga yang sementara tinggal di luar desanya.', '1 hari kerja', '["Fotokopi KTP & KK", "Surat pengantar RT/RW"]', '[{"key": "alamat_sementara", "label": "Alamat Sementara", "type": "textarea", "required": true, "colSpan": 2}, {"key": "alasan", "label": "Alasan Tinggal Sementara", "type": "select", "options": ["Kerja", "Sekolah", "Merantau", "Lainnya"], "required": true}, {"key": "lama_tinggal", "label": "Perkiraan Lama Tinggal", "type": "text", "required": true}]', 'Disetujui'),
('SP_KTP', 'Surat Pengantar Pembuatan KTP', 'Kependudukan', 'Pengantar pembuatan KTP. Wewenang penuh.', '1 hari kerja', '["Fotokopi KK", "Pas foto 3x4"]', '[{"key": "jenis_permohonan", "label": "Jenis Permohonan", "type": "select", "options": ["Baru", "Perpanjangan", "Hilang/Rusak", "Perubahan Data"], "required": true}, {"key": "alasan", "label": "Keterangan", "type": "textarea", "colSpan": 2}]', 'Disetujui'),
('SP_KK', 'Surat Pengantar Pembuatan KK', 'Kependudukan', 'Pengganti ELIMINASI KK Sementara.', '1 hari kerja', '["KK lama", "Akta nikah/kelahiran (jika perubahan)"]', '[{"key": "jenis_perubahan", "label": "Jenis Perubahan", "type": "select", "options": ["Penambahan Anggota", "Pengurangan Anggota", "Pisah KK", "KK Baru"], "required": true}, {"key": "keterangan", "label": "Keterangan", "type": "textarea", "colSpan": 2}]', 'Disetujui'),
('SKTM', 'Surat Keterangan Tidak Mampu (SKTM)', 'Sosial & Ekonomi', 'SURAT PALING PENTING. Akses BPJS PBI, beasiswa, bantuan sosial.', '1 hari kerja', '["Fotokopi KTP & KK", "Pengantar RT/RW", "Foto rumah (opsional)"]', '[{"key": "penghasilan", "label": "Penghasilan per Bulan (Rp)", "type": "number", "required": true, "autofill": "pendapatan_bulan"}, {"key": "tanggungan", "label": "Jumlah Tanggungan", "type": "number", "required": true}, {"key": "keperluan", "label": "Keperluan", "type": "textarea", "placeholder": "Contoh: Pengajuan beasiswa KIP-Kuliah", "required": true, "colSpan": 2}, {"key": "id_bdt", "label": "ID BDTPBIDTKS (jika sudah terintegrasi DTKS)", "type": "text", "placeholder": "Kosongkan jika belum teregistrasi DTKS", "colSpan": 2}, {"key": "program_bantuan", "label": "Program Bantuan yang Dituju", "type": "multiselect", "options": ["PKH", "BPNT", "PBI JKN (BPJS)", "KIP", "BLSM", "Program Desa", "Lainnya"], "colSpan": 2}, {"key": "no_kartu_bantuan", "label": "No. Kartu Bantuan (jika sudah memiliki)", "type": "text", "colSpan": 2}]', 'Disetujui'),
('SK_PENGHASILAN', 'Surat Keterangan Penghasilan', 'Sosial & Ekonomi', 'Untuk KUR (Kredit Usaha Rakyat), pendaftaran sekolah, dan lainnya.', '1 hari kerja', '["Fotokopi KTP & KK", "Pengantar RT/RW"]', '[{"key": "penghasilan", "label": "Penghasilan per Bulan (Rp)", "type": "number", "required": true, "autofill": "pendapatan_bulan"}, {"key": "sumber_penghasilan", "label": "Sumber Penghasilan", "type": "text", "required": true, "autofill": "pekerjaan"}, {"key": "keperluan", "label": "Keperluan", "type": "textarea", "required": true, "colSpan": 2}, {"key": "nama_ayah", "label": "Nama Lengkap Ayah", "type": "text", "required": true, "autofill": "nama_bapak"}, {"key": "nik_ayah", "label": "NIK Ayah", "type": "text", "required": true}, {"key": "tanggal_lahir_ayah", "label": "Tanggal Lahir Ayah", "type": "date"}, {"key": "tempat_lahir_ayah", "label": "Tempat Lahir Ayah", "type": "text"}, {"key": "pekerjaan_ayah", "label": "Pekerjaan Ayah", "type": "text"}, {"key": "penghasilan_ayah", "label": "Penghasilan Ayah/Bulan (Rp)", "type": "text"}, {"key": "alamat_ayah", "label": "Alamat Ayah", "type": "textarea"}, {"key": "nama_ibu", "label": "Nama Lengkap Ibu", "type": "text", "required": true, "autofill": "nama_ibu"}, {"key": "nik_ibu", "label": "NIK Ibu", "type": "text", "required": true}, {"key": "tanggal_lahir_ibu", "label": "Tanggal Lahir Ibu", "type": "date"}, {"key": "tempat_lahir_ibu", "label": "Tempat Lahir Ibu", "type": "text"}, {"key": "pekerjaan_ibu", "label": "Pekerjaan Ibu", "type": "text"}, {"key": "penghasilan_ibu", "label": "Penghasilan Ibu/Bulan (Rp)", "type": "text"}, {"key": "alamat_ibu", "label": "Alamat Ibu", "type": "textarea"}, {"key": "nama_sekolah", "label": "Nama Sekolah/Perguruan Tinggi", "type": "text"}, {"key": "jurusan", "label": "Jurusan/Fakultas/Program Studi", "type": "text"}, {"key": "kelas_semester", "label": "Kelas/Semester", "type": "text"}, {"key": "nomor_induk", "label": "Nomor Induk Siswa/Mahasiswa", "type": "text"}]', 'Disetujui'),
('SKU', 'Surat Keterangan Usaha (SKU)', 'Usaha & Ekonomi', 'SURAT PALING PENTING kategori usaha. Syarat NIB.', '2 hari kerja', '["Fotokopi KTP", "Foto tempat usaha", "Pengantar RT/RW"]', '[{"key": "nama_usaha", "label": "Nama Usaha", "type": "text", "required": true}, {"key": "keperluan", "label": "Keperluan", "type": "textarea", "placeholder": "Jelaskan keperluan pengajuan surat ini...", "required": true, "colSpan": 2}, {"key": "jenis_usaha", "label": "Jenis Usaha", "type": "select", "options": ["Perdagangan", "Jasa", "Pertanian", "Industri Rumahan", "Lainnya"], "required": true}, {"key": "alamat_usaha", "label": "Alamat Usaha", "type": "textarea", "required": true, "colSpan": 2, "autofill": "alamat"}, {"key": "tahun_berdiri", "label": "Tahun Berdiri", "type": "number", "required": true}, {"key": "jumlah_karyawan", "label": "Jumlah Karyawan", "type": "number", "placeholder": "0"}]', 'Disetujui');
