/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifikasiRouteImport } from './routes/verifikasi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WisataUmkmRouteImport } from './routes/wisata.umkm'
import { Route as WisataDestinasiRouteImport } from './routes/wisata.destinasi'
import { Route as VerifikasiNoRouteImport } from './routes/verifikasi.$no'
import { Route as ProfilPkkrwRouteImport } from './routes/profil.pkkrw'
import { Route as ProfilPerangkatRouteImport } from './routes/profil.perangkat'
import { Route as ProfilLpmRouteImport } from './routes/profil.lpm'
import { Route as ProfilLembagaRouteImport } from './routes/profil.lembaga'
import { Route as ProfilKarangtarunaRouteImport } from './routes/profil.karangtaruna'
import { Route as ProfilDesaRouteImport } from './routes/profil.desa'
import { Route as ProfilBpdRouteImport } from './routes/profil.bpd'
import { Route as PelayananSuratTerbitRouteImport } from './routes/pelayanan.surat-terbit'
import { Route as PelayananPengaduanRouteImport } from './routes/pelayanan.pengaduan'
import { Route as PelayananPendudukRouteImport } from './routes/pelayanan.penduduk'
import { Route as PelayananMonitoringRouteImport } from './routes/pelayanan.monitoring'
import { Route as PelayananLacakRouteImport } from './routes/pelayanan.lacak'
import { Route as PelayananESuratRouteImport } from './routes/pelayanan.e-surat'
import { Route as MasukWargaRouteImport } from './routes/masuk.warga'
import { Route as MasukPengajuanSayaRouteImport } from './routes/masuk.pengajuan-saya'
import { Route as MasukEditSuratRouteImport } from './routes/masuk.edit-surat'
import { Route as LaporanApbdesRouteImport } from './routes/laporan.apbdes'
import { Route as LainnyaProdukHukumRouteImport } from './routes/lainnya.produk-hukum'
import { Route as LainnyaPotensiDesaRouteImport } from './routes/lainnya.potensi-desa'
import { Route as LainnyaPetaRouteImport } from './routes/lainnya.peta'
import { Route as LainnyaMonografiRouteImport } from './routes/lainnya.monografi'
import { Route as LainnyaKomoditasRouteImport } from './routes/lainnya.komoditas'
import { Route as InformasiStatistikRouteImport } from './routes/informasi.statistik'
import { Route as InformasiPengumumanRouteImport } from './routes/informasi.pengumuman'
import { Route as InformasiIdmRouteImport } from './routes/informasi.idm'
import { Route as InformasiGaleriRouteImport } from './routes/informasi.galeri'
import { Route as InformasiBeritaRouteImport } from './routes/informasi.berita'
import { Route as InformasiAgendaRouteImport } from './routes/informasi.agenda'
import { Route as AdminMonitoringSuratRouteImport } from './routes/admin.monitoring-surat'
import { Route as AdminLaporanRwRouteImport } from './routes/admin.laporan-rw'
import { Route as InformasiBeritaSlugRouteImport } from './routes/informasi.berita.$slug'

const VerifikasiRoute = VerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WisataUmkmRoute = WisataUmkmRouteImport.update({
  id: '/wisata/umkm',
  path: '/wisata/umkm',
  getParentRoute: () => rootRouteImport,
} as any)
const WisataDestinasiRoute = WisataDestinasiRouteImport.update({
  id: '/wisata/destinasi',
  path: '/wisata/destinasi',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifikasiNoRoute = VerifikasiNoRouteImport.update({
  id: '/$no',
  path: '/$no',
  getParentRoute: () => VerifikasiRoute,
} as any)
const ProfilPkkrwRoute = ProfilPkkrwRouteImport.update({
  id: '/profil/pkkrw',
  path: '/profil/pkkrw',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilPerangkatRoute = ProfilPerangkatRouteImport.update({
  id: '/profil/perangkat',
  path: '/profil/perangkat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilLpmRoute = ProfilLpmRouteImport.update({
  id: '/profil/lpm',
  path: '/profil/lpm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilLembagaRoute = ProfilLembagaRouteImport.update({
  id: '/profil/lembaga',
  path: '/profil/lembaga',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilKarangtarunaRoute = ProfilKarangtarunaRouteImport.update({
  id: '/profil/karangtaruna',
  path: '/profil/karangtaruna',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilDesaRoute = ProfilDesaRouteImport.update({
  id: '/profil/desa',
  path: '/profil/desa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilBpdRoute = ProfilBpdRouteImport.update({
  id: '/profil/bpd',
  path: '/profil/bpd',
  getParentRoute: () => rootRouteImport,
} as any)
const PelayananSuratTerbitRoute = PelayananSuratTerbitRouteImport.update({
  id: '/pelayanan/surat-terbit',
  path: '/pelayanan/surat-terbit',
  getParentRoute: () => rootRouteImport,
} as any)
const PelayananPengaduanRoute = PelayananPengaduanRouteImport.update({
  id: '/pelayanan/pengaduan',
  path: '/pelayanan/pengaduan',
  getParentRoute: () => rootRouteImport,
} as any)
const PelayananPendudukRoute = PelayananPendudukRouteImport.update({
  id: '/pelayanan/penduduk',
  path: '/pelayanan/penduduk',
  getParentRoute: () => rootRouteImport,
} as any)
const PelayananMonitoringRoute = PelayananMonitoringRouteImport.update({
  id: '/pelayanan/monitoring',
  path: '/pelayanan/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PelayananLacakRoute = PelayananLacakRouteImport.update({
  id: '/pelayanan/lacak',
  path: '/pelayanan/lacak',
  getParentRoute: () => rootRouteImport,
} as any)
const PelayananESuratRoute = PelayananESuratRouteImport.update({
  id: '/pelayanan/e-surat',
  path: '/pelayanan/e-surat',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukWargaRoute = MasukWargaRouteImport.update({
  id: '/masuk/warga',
  path: '/masuk/warga',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukPengajuanSayaRoute = MasukPengajuanSayaRouteImport.update({
  id: '/masuk/pengajuan-saya',
  path: '/masuk/pengajuan-saya',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukEditSuratRoute = MasukEditSuratRouteImport.update({
  id: '/masuk/edit-surat',
  path: '/masuk/edit-surat',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanApbdesRoute = LaporanApbdesRouteImport.update({
  id: '/laporan/apbdes',
  path: '/laporan/apbdes',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaProdukHukumRoute = LainnyaProdukHukumRouteImport.update({
  id: '/lainnya/produk-hukum',
  path: '/lainnya/produk-hukum',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaPotensiDesaRoute = LainnyaPotensiDesaRouteImport.update({
  id: '/lainnya/potensi-desa',
  path: '/lainnya/potensi-desa',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaPetaRoute = LainnyaPetaRouteImport.update({
  id: '/lainnya/peta',
  path: '/lainnya/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaMonografiRoute = LainnyaMonografiRouteImport.update({
  id: '/lainnya/monografi',
  path: '/lainnya/monografi',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaKomoditasRoute = LainnyaKomoditasRouteImport.update({
  id: '/lainnya/komoditas',
  path: '/lainnya/komoditas',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiStatistikRoute = InformasiStatistikRouteImport.update({
  id: '/informasi/statistik',
  path: '/informasi/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiPengumumanRoute = InformasiPengumumanRouteImport.update({
  id: '/informasi/pengumuman',
  path: '/informasi/pengumuman',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiIdmRoute = InformasiIdmRouteImport.update({
  id: '/informasi/idm',
  path: '/informasi/idm',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiGaleriRoute = InformasiGaleriRouteImport.update({
  id: '/informasi/galeri',
  path: '/informasi/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiBeritaRoute = InformasiBeritaRouteImport.update({
  id: '/informasi/berita',
  path: '/informasi/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiAgendaRoute = InformasiAgendaRouteImport.update({
  id: '/informasi/agenda',
  path: '/informasi/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringSuratRoute = AdminMonitoringSuratRouteImport.update({
  id: '/monitoring-surat',
  path: '/monitoring-surat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaporanRwRoute = AdminLaporanRwRouteImport.update({
  id: '/laporan-rw',
  path: '/laporan-rw',
  getParentRoute: () => AdminRoute,
} as any)
const InformasiBeritaSlugRoute = InformasiBeritaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InformasiBeritaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/verifikasi': typeof VerifikasiRouteWithChildren
  '/admin/laporan-rw': typeof AdminLaporanRwRoute
  '/admin/monitoring-surat': typeof AdminMonitoringSuratRoute
  '/informasi/agenda': typeof InformasiAgendaRoute
  '/informasi/berita': typeof InformasiBeritaRouteWithChildren
  '/informasi/galeri': typeof InformasiGaleriRoute
  '/informasi/idm': typeof InformasiIdmRoute
  '/informasi/pengumuman': typeof InformasiPengumumanRoute
  '/informasi/statistik': typeof InformasiStatistikRoute
  '/lainnya/komoditas': typeof LainnyaKomoditasRoute
  '/lainnya/monografi': typeof LainnyaMonografiRoute
  '/lainnya/peta': typeof LainnyaPetaRoute
  '/lainnya/potensi-desa': typeof LainnyaPotensiDesaRoute
  '/lainnya/produk-hukum': typeof LainnyaProdukHukumRoute
  '/laporan/apbdes': typeof LaporanApbdesRoute
  '/masuk/edit-surat': typeof MasukEditSuratRoute
  '/masuk/pengajuan-saya': typeof MasukPengajuanSayaRoute
  '/masuk/warga': typeof MasukWargaRoute
  '/pelayanan/e-surat': typeof PelayananESuratRoute
  '/pelayanan/lacak': typeof PelayananLacakRoute
  '/pelayanan/monitoring': typeof PelayananMonitoringRoute
  '/pelayanan/penduduk': typeof PelayananPendudukRoute
  '/pelayanan/pengaduan': typeof PelayananPengaduanRoute
  '/pelayanan/surat-terbit': typeof PelayananSuratTerbitRoute
  '/profil/bpd': typeof ProfilBpdRoute
  '/profil/desa': typeof ProfilDesaRoute
  '/profil/karangtaruna': typeof ProfilKarangtarunaRoute
  '/profil/lembaga': typeof ProfilLembagaRoute
  '/profil/lpm': typeof ProfilLpmRoute
  '/profil/perangkat': typeof ProfilPerangkatRoute
  '/profil/pkkrw': typeof ProfilPkkrwRoute
  '/verifikasi/$no': typeof VerifikasiNoRoute
  '/wisata/destinasi': typeof WisataDestinasiRoute
  '/wisata/umkm': typeof WisataUmkmRoute
  '/informasi/berita/$slug': typeof InformasiBeritaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/verifikasi': typeof VerifikasiRouteWithChildren
  '/admin/laporan-rw': typeof AdminLaporanRwRoute
  '/admin/monitoring-surat': typeof AdminMonitoringSuratRoute
  '/informasi/agenda': typeof InformasiAgendaRoute
  '/informasi/berita': typeof InformasiBeritaRouteWithChildren
  '/informasi/galeri': typeof InformasiGaleriRoute
  '/informasi/idm': typeof InformasiIdmRoute
  '/informasi/pengumuman': typeof InformasiPengumumanRoute
  '/informasi/statistik': typeof InformasiStatistikRoute
  '/lainnya/komoditas': typeof LainnyaKomoditasRoute
  '/lainnya/monografi': typeof LainnyaMonografiRoute
  '/lainnya/peta': typeof LainnyaPetaRoute
  '/lainnya/potensi-desa': typeof LainnyaPotensiDesaRoute
  '/lainnya/produk-hukum': typeof LainnyaProdukHukumRoute
  '/laporan/apbdes': typeof LaporanApbdesRoute
  '/masuk/edit-surat': typeof MasukEditSuratRoute
  '/masuk/pengajuan-saya': typeof MasukPengajuanSayaRoute
  '/masuk/warga': typeof MasukWargaRoute
  '/pelayanan/e-surat': typeof PelayananESuratRoute
  '/pelayanan/lacak': typeof PelayananLacakRoute
  '/pelayanan/monitoring': typeof PelayananMonitoringRoute
  '/pelayanan/penduduk': typeof PelayananPendudukRoute
  '/pelayanan/pengaduan': typeof PelayananPengaduanRoute
  '/pelayanan/surat-terbit': typeof PelayananSuratTerbitRoute
  '/profil/bpd': typeof ProfilBpdRoute
  '/profil/desa': typeof ProfilDesaRoute
  '/profil/karangtaruna': typeof ProfilKarangtarunaRoute
  '/profil/lembaga': typeof ProfilLembagaRoute
  '/profil/lpm': typeof ProfilLpmRoute
  '/profil/perangkat': typeof ProfilPerangkatRoute
  '/profil/pkkrw': typeof ProfilPkkrwRoute
  '/verifikasi/$no': typeof VerifikasiNoRoute
  '/wisata/destinasi': typeof WisataDestinasiRoute
  '/wisata/umkm': typeof WisataUmkmRoute
  '/informasi/berita/$slug': typeof InformasiBeritaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/verifikasi': typeof VerifikasiRouteWithChildren
  '/admin/laporan-rw': typeof AdminLaporanRwRoute
  '/admin/monitoring-surat': typeof AdminMonitoringSuratRoute
  '/informasi/agenda': typeof InformasiAgendaRoute
  '/informasi/berita': typeof InformasiBeritaRouteWithChildren
  '/informasi/galeri': typeof InformasiGaleriRoute
  '/informasi/idm': typeof InformasiIdmRoute
  '/informasi/pengumuman': typeof InformasiPengumumanRoute
  '/informasi/statistik': typeof InformasiStatistikRoute
  '/lainnya/komoditas': typeof LainnyaKomoditasRoute
  '/lainnya/monografi': typeof LainnyaMonografiRoute
  '/lainnya/peta': typeof LainnyaPetaRoute
  '/lainnya/potensi-desa': typeof LainnyaPotensiDesaRoute
  '/lainnya/produk-hukum': typeof LainnyaProdukHukumRoute
  '/laporan/apbdes': typeof LaporanApbdesRoute
  '/masuk/edit-surat': typeof MasukEditSuratRoute
  '/masuk/pengajuan-saya': typeof MasukPengajuanSayaRoute
  '/masuk/warga': typeof MasukWargaRoute
  '/pelayanan/e-surat': typeof PelayananESuratRoute
  '/pelayanan/lacak': typeof PelayananLacakRoute
  '/pelayanan/monitoring': typeof PelayananMonitoringRoute
  '/pelayanan/penduduk': typeof PelayananPendudukRoute
  '/pelayanan/pengaduan': typeof PelayananPengaduanRoute
  '/pelayanan/surat-terbit': typeof PelayananSuratTerbitRoute
  '/profil/bpd': typeof ProfilBpdRoute
  '/profil/desa': typeof ProfilDesaRoute
  '/profil/karangtaruna': typeof ProfilKarangtarunaRoute
  '/profil/lembaga': typeof ProfilLembagaRoute
  '/profil/lpm': typeof ProfilLpmRoute
  '/profil/perangkat': typeof ProfilPerangkatRoute
  '/profil/pkkrw': typeof ProfilPkkrwRoute
  '/verifikasi/$no': typeof VerifikasiNoRoute
  '/wisata/destinasi': typeof WisataDestinasiRoute
  '/wisata/umkm': typeof WisataUmkmRoute
  '/informasi/berita/$slug': typeof InformasiBeritaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/login'
    | '/verifikasi'
    | '/admin/laporan-rw'
    | '/admin/monitoring-surat'
    | '/informasi/agenda'
    | '/informasi/berita'
    | '/informasi/galeri'
    | '/informasi/idm'
    | '/informasi/pengumuman'
    | '/informasi/statistik'
    | '/lainnya/komoditas'
    | '/lainnya/monografi'
    | '/lainnya/peta'
    | '/lainnya/potensi-desa'
    | '/lainnya/produk-hukum'
    | '/laporan/apbdes'
    | '/masuk/edit-surat'
    | '/masuk/pengajuan-saya'
    | '/masuk/warga'
    | '/pelayanan/e-surat'
    | '/pelayanan/lacak'
    | '/pelayanan/monitoring'
    | '/pelayanan/penduduk'
    | '/pelayanan/pengaduan'
    | '/pelayanan/surat-terbit'
    | '/profil/bpd'
    | '/profil/desa'
    | '/profil/karangtaruna'
    | '/profil/lembaga'
    | '/profil/lpm'
    | '/profil/perangkat'
    | '/profil/pkkrw'
    | '/verifikasi/$no'
    | '/wisata/destinasi'
    | '/wisata/umkm'
    | '/informasi/berita/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/login'
    | '/verifikasi'
    | '/admin/laporan-rw'
    | '/admin/monitoring-surat'
    | '/informasi/agenda'
    | '/informasi/berita'
    | '/informasi/galeri'
    | '/informasi/idm'
    | '/informasi/pengumuman'
    | '/informasi/statistik'
    | '/lainnya/komoditas'
    | '/lainnya/monografi'
    | '/lainnya/peta'
    | '/lainnya/potensi-desa'
    | '/lainnya/produk-hukum'
    | '/laporan/apbdes'
    | '/masuk/edit-surat'
    | '/masuk/pengajuan-saya'
    | '/masuk/warga'
    | '/pelayanan/e-surat'
    | '/pelayanan/lacak'
    | '/pelayanan/monitoring'
    | '/pelayanan/penduduk'
    | '/pelayanan/pengaduan'
    | '/pelayanan/surat-terbit'
    | '/profil/bpd'
    | '/profil/desa'
    | '/profil/karangtaruna'
    | '/profil/lembaga'
    | '/profil/lpm'
    | '/profil/perangkat'
    | '/profil/pkkrw'
    | '/verifikasi/$no'
    | '/wisata/destinasi'
    | '/wisata/umkm'
    | '/informasi/berita/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/login'
    | '/verifikasi'
    | '/admin/laporan-rw'
    | '/admin/monitoring-surat'
    | '/informasi/agenda'
    | '/informasi/berita'
    | '/informasi/galeri'
    | '/informasi/idm'
    | '/informasi/pengumuman'
    | '/informasi/statistik'
    | '/lainnya/komoditas'
    | '/lainnya/monografi'
    | '/lainnya/peta'
    | '/lainnya/potensi-desa'
    | '/lainnya/produk-hukum'
    | '/laporan/apbdes'
    | '/masuk/edit-surat'
    | '/masuk/pengajuan-saya'
    | '/masuk/warga'
    | '/pelayanan/e-surat'
    | '/pelayanan/lacak'
    | '/pelayanan/monitoring'
    | '/pelayanan/penduduk'
    | '/pelayanan/pengaduan'
    | '/pelayanan/surat-terbit'
    | '/profil/bpd'
    | '/profil/desa'
    | '/profil/karangtaruna'
    | '/profil/lembaga'
    | '/profil/lpm'
    | '/profil/perangkat'
    | '/profil/pkkrw'
    | '/verifikasi/$no'
    | '/wisata/destinasi'
    | '/wisata/umkm'
    | '/informasi/berita/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifikasiRoute: typeof VerifikasiRouteWithChildren
  InformasiAgendaRoute: typeof InformasiAgendaRoute
  InformasiBeritaRoute: typeof InformasiBeritaRouteWithChildren
  InformasiGaleriRoute: typeof InformasiGaleriRoute
  InformasiIdmRoute: typeof InformasiIdmRoute
  InformasiPengumumanRoute: typeof InformasiPengumumanRoute
  InformasiStatistikRoute: typeof InformasiStatistikRoute
  LainnyaKomoditasRoute: typeof LainnyaKomoditasRoute
  LainnyaMonografiRoute: typeof LainnyaMonografiRoute
  LainnyaPetaRoute: typeof LainnyaPetaRoute
  LainnyaPotensiDesaRoute: typeof LainnyaPotensiDesaRoute
  LainnyaProdukHukumRoute: typeof LainnyaProdukHukumRoute
  LaporanApbdesRoute: typeof LaporanApbdesRoute
  MasukEditSuratRoute: typeof MasukEditSuratRoute
  MasukPengajuanSayaRoute: typeof MasukPengajuanSayaRoute
  MasukWargaRoute: typeof MasukWargaRoute
  PelayananESuratRoute: typeof PelayananESuratRoute
  PelayananLacakRoute: typeof PelayananLacakRoute
  PelayananMonitoringRoute: typeof PelayananMonitoringRoute
  PelayananPendudukRoute: typeof PelayananPendudukRoute
  PelayananPengaduanRoute: typeof PelayananPengaduanRoute
  PelayananSuratTerbitRoute: typeof PelayananSuratTerbitRoute
  ProfilBpdRoute: typeof ProfilBpdRoute
  ProfilDesaRoute: typeof ProfilDesaRoute
  ProfilKarangtarunaRoute: typeof ProfilKarangtarunaRoute
  ProfilLembagaRoute: typeof ProfilLembagaRoute
  ProfilLpmRoute: typeof ProfilLpmRoute
  ProfilPerangkatRoute: typeof ProfilPerangkatRoute
  ProfilPkkrwRoute: typeof ProfilPkkrwRoute
  WisataDestinasiRoute: typeof WisataDestinasiRoute
  WisataUmkmRoute: typeof WisataUmkmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verifikasi': {
      id: '/verifikasi'
      path: '/verifikasi'
      fullPath: '/verifikasi'
      preLoaderRoute: typeof VerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisata/umkm': {
      id: '/wisata/umkm'
      path: '/wisata/umkm'
      fullPath: '/wisata/umkm'
      preLoaderRoute: typeof WisataUmkmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisata/destinasi': {
      id: '/wisata/destinasi'
      path: '/wisata/destinasi'
      fullPath: '/wisata/destinasi'
      preLoaderRoute: typeof WisataDestinasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifikasi/$no': {
      id: '/verifikasi/$no'
      path: '/$no'
      fullPath: '/verifikasi/$no'
      preLoaderRoute: typeof VerifikasiNoRouteImport
      parentRoute: typeof VerifikasiRoute
    }
    '/profil/pkkrw': {
      id: '/profil/pkkrw'
      path: '/profil/pkkrw'
      fullPath: '/profil/pkkrw'
      preLoaderRoute: typeof ProfilPkkrwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/perangkat': {
      id: '/profil/perangkat'
      path: '/profil/perangkat'
      fullPath: '/profil/perangkat'
      preLoaderRoute: typeof ProfilPerangkatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/lpm': {
      id: '/profil/lpm'
      path: '/profil/lpm'
      fullPath: '/profil/lpm'
      preLoaderRoute: typeof ProfilLpmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/lembaga': {
      id: '/profil/lembaga'
      path: '/profil/lembaga'
      fullPath: '/profil/lembaga'
      preLoaderRoute: typeof ProfilLembagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/karangtaruna': {
      id: '/profil/karangtaruna'
      path: '/profil/karangtaruna'
      fullPath: '/profil/karangtaruna'
      preLoaderRoute: typeof ProfilKarangtarunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/desa': {
      id: '/profil/desa'
      path: '/profil/desa'
      fullPath: '/profil/desa'
      preLoaderRoute: typeof ProfilDesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/bpd': {
      id: '/profil/bpd'
      path: '/profil/bpd'
      fullPath: '/profil/bpd'
      preLoaderRoute: typeof ProfilBpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelayanan/surat-terbit': {
      id: '/pelayanan/surat-terbit'
      path: '/pelayanan/surat-terbit'
      fullPath: '/pelayanan/surat-terbit'
      preLoaderRoute: typeof PelayananSuratTerbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelayanan/pengaduan': {
      id: '/pelayanan/pengaduan'
      path: '/pelayanan/pengaduan'
      fullPath: '/pelayanan/pengaduan'
      preLoaderRoute: typeof PelayananPengaduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelayanan/penduduk': {
      id: '/pelayanan/penduduk'
      path: '/pelayanan/penduduk'
      fullPath: '/pelayanan/penduduk'
      preLoaderRoute: typeof PelayananPendudukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelayanan/monitoring': {
      id: '/pelayanan/monitoring'
      path: '/pelayanan/monitoring'
      fullPath: '/pelayanan/monitoring'
      preLoaderRoute: typeof PelayananMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelayanan/lacak': {
      id: '/pelayanan/lacak'
      path: '/pelayanan/lacak'
      fullPath: '/pelayanan/lacak'
      preLoaderRoute: typeof PelayananLacakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelayanan/e-surat': {
      id: '/pelayanan/e-surat'
      path: '/pelayanan/e-surat'
      fullPath: '/pelayanan/e-surat'
      preLoaderRoute: typeof PelayananESuratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk/warga': {
      id: '/masuk/warga'
      path: '/masuk/warga'
      fullPath: '/masuk/warga'
      preLoaderRoute: typeof MasukWargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk/pengajuan-saya': {
      id: '/masuk/pengajuan-saya'
      path: '/masuk/pengajuan-saya'
      fullPath: '/masuk/pengajuan-saya'
      preLoaderRoute: typeof MasukPengajuanSayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk/edit-surat': {
      id: '/masuk/edit-surat'
      path: '/masuk/edit-surat'
      fullPath: '/masuk/edit-surat'
      preLoaderRoute: typeof MasukEditSuratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/apbdes': {
      id: '/laporan/apbdes'
      path: '/laporan/apbdes'
      fullPath: '/laporan/apbdes'
      preLoaderRoute: typeof LaporanApbdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya/produk-hukum': {
      id: '/lainnya/produk-hukum'
      path: '/lainnya/produk-hukum'
      fullPath: '/lainnya/produk-hukum'
      preLoaderRoute: typeof LainnyaProdukHukumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya/potensi-desa': {
      id: '/lainnya/potensi-desa'
      path: '/lainnya/potensi-desa'
      fullPath: '/lainnya/potensi-desa'
      preLoaderRoute: typeof LainnyaPotensiDesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya/peta': {
      id: '/lainnya/peta'
      path: '/lainnya/peta'
      fullPath: '/lainnya/peta'
      preLoaderRoute: typeof LainnyaPetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya/monografi': {
      id: '/lainnya/monografi'
      path: '/lainnya/monografi'
      fullPath: '/lainnya/monografi'
      preLoaderRoute: typeof LainnyaMonografiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya/komoditas': {
      id: '/lainnya/komoditas'
      path: '/lainnya/komoditas'
      fullPath: '/lainnya/komoditas'
      preLoaderRoute: typeof LainnyaKomoditasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/statistik': {
      id: '/informasi/statistik'
      path: '/informasi/statistik'
      fullPath: '/informasi/statistik'
      preLoaderRoute: typeof InformasiStatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/pengumuman': {
      id: '/informasi/pengumuman'
      path: '/informasi/pengumuman'
      fullPath: '/informasi/pengumuman'
      preLoaderRoute: typeof InformasiPengumumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/idm': {
      id: '/informasi/idm'
      path: '/informasi/idm'
      fullPath: '/informasi/idm'
      preLoaderRoute: typeof InformasiIdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/galeri': {
      id: '/informasi/galeri'
      path: '/informasi/galeri'
      fullPath: '/informasi/galeri'
      preLoaderRoute: typeof InformasiGaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/berita': {
      id: '/informasi/berita'
      path: '/informasi/berita'
      fullPath: '/informasi/berita'
      preLoaderRoute: typeof InformasiBeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/agenda': {
      id: '/informasi/agenda'
      path: '/informasi/agenda'
      fullPath: '/informasi/agenda'
      preLoaderRoute: typeof InformasiAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring-surat': {
      id: '/admin/monitoring-surat'
      path: '/monitoring-surat'
      fullPath: '/admin/monitoring-surat'
      preLoaderRoute: typeof AdminMonitoringSuratRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/laporan-rw': {
      id: '/admin/laporan-rw'
      path: '/laporan-rw'
      fullPath: '/admin/laporan-rw'
      preLoaderRoute: typeof AdminLaporanRwRouteImport
      parentRoute: typeof AdminRoute
    }
    '/informasi/berita/$slug': {
      id: '/informasi/berita/$slug'
      path: '/$slug'
      fullPath: '/informasi/berita/$slug'
      preLoaderRoute: typeof InformasiBeritaSlugRouteImport
      parentRoute: typeof InformasiBeritaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLaporanRwRoute: typeof AdminLaporanRwRoute
  AdminMonitoringSuratRoute: typeof AdminMonitoringSuratRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLaporanRwRoute: AdminLaporanRwRoute,
  AdminMonitoringSuratRoute: AdminMonitoringSuratRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VerifikasiRouteChildren {
  VerifikasiNoRoute: typeof VerifikasiNoRoute
}

const VerifikasiRouteChildren: VerifikasiRouteChildren = {
  VerifikasiNoRoute: VerifikasiNoRoute,
}

const VerifikasiRouteWithChildren = VerifikasiRoute._addFileChildren(
  VerifikasiRouteChildren,
)

interface InformasiBeritaRouteChildren {
  InformasiBeritaSlugRoute: typeof InformasiBeritaSlugRoute
}

const InformasiBeritaRouteChildren: InformasiBeritaRouteChildren = {
  InformasiBeritaSlugRoute: InformasiBeritaSlugRoute,
}

const InformasiBeritaRouteWithChildren = InformasiBeritaRoute._addFileChildren(
  InformasiBeritaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifikasiRoute: VerifikasiRouteWithChildren,
  InformasiAgendaRoute: InformasiAgendaRoute,
  InformasiBeritaRoute: InformasiBeritaRouteWithChildren,
  InformasiGaleriRoute: InformasiGaleriRoute,
  InformasiIdmRoute: InformasiIdmRoute,
  InformasiPengumumanRoute: InformasiPengumumanRoute,
  InformasiStatistikRoute: InformasiStatistikRoute,
  LainnyaKomoditasRoute: LainnyaKomoditasRoute,
  LainnyaMonografiRoute: LainnyaMonografiRoute,
  LainnyaPetaRoute: LainnyaPetaRoute,
  LainnyaPotensiDesaRoute: LainnyaPotensiDesaRoute,
  LainnyaProdukHukumRoute: LainnyaProdukHukumRoute,
  LaporanApbdesRoute: LaporanApbdesRoute,
  MasukEditSuratRoute: MasukEditSuratRoute,
  MasukPengajuanSayaRoute: MasukPengajuanSayaRoute,
  MasukWargaRoute: MasukWargaRoute,
  PelayananESuratRoute: PelayananESuratRoute,
  PelayananLacakRoute: PelayananLacakRoute,
  PelayananMonitoringRoute: PelayananMonitoringRoute,
  PelayananPendudukRoute: PelayananPendudukRoute,
  PelayananPengaduanRoute: PelayananPengaduanRoute,
  PelayananSuratTerbitRoute: PelayananSuratTerbitRoute,
  ProfilBpdRoute: ProfilBpdRoute,
  ProfilDesaRoute: ProfilDesaRoute,
  ProfilKarangtarunaRoute: ProfilKarangtarunaRoute,
  ProfilLembagaRoute: ProfilLembagaRoute,
  ProfilLpmRoute: ProfilLpmRoute,
  ProfilPerangkatRoute: ProfilPerangkatRoute,
  ProfilPkkrwRoute: ProfilPkkrwRoute,
  WisataDestinasiRoute: WisataDestinasiRoute,
  WisataUmkmRoute: WisataUmkmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
