/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifikasiNoRouteImport } from './routes/verifikasi.$no'
import { Route as ProfilPkkrwRouteImport } from './routes/profil.pkkrw'
import { Route as ProfilPerangkatRouteImport } from './routes/profil.perangkat'
import { Route as ProfilLpmRouteImport } from './routes/profil.lpm'
import { Route as ProfilLembagaRouteImport } from './routes/profil.lembaga'
import { Route as ProfilKarangtarunaRouteImport } from './routes/profil.karangtaruna'
import { Route as ProfilBpdRouteImport } from './routes/profil.bpd'
import { Route as PelayananPendudukRouteImport } from './routes/pelayanan.penduduk'
import { Route as PelayananMonitoringRouteImport } from './routes/pelayanan.monitoring'
import { Route as PelayananESuratRouteImport } from './routes/pelayanan.e-surat'
import { Route as LaporanApbdesRouteImport } from './routes/laporan.apbdes'
import { Route as LainnyaPetaRouteImport } from './routes/lainnya.peta'
import { Route as InformasiBeritaRouteImport } from './routes/informasi.berita'
import { Route as InformasiAgendaRouteImport } from './routes/informasi.agenda'
import { Route as EkonomiBumdesRouteImport } from './routes/ekonomi.bumdes'
import { Route as InformasiBeritaSlugRouteImport } from './routes/informasi.berita.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifikasiNoRoute = VerifikasiNoRouteImport.update({
  id: '/verifikasi/$no',
  path: '/verifikasi/$no',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilPkkrwRoute = ProfilPkkrwRouteImport.update({
  id: '/profil/pkkrw',
  path: '/profil/pkkrw',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilPerangkatRoute = ProfilPerangkatRouteImport.update({
  id: '/profil/perangkat',
  path: '/profil/perangkat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilLpmRoute = ProfilLpmRouteImport.update({
  id: '/profil/lpm',
  path: '/profil/lpm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilLembagaRoute = ProfilLembagaRouteImport.update({
  id: '/profil/lembaga',
  path: '/profil/lembaga',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilKarangtarunaRoute = ProfilKarangtarunaRouteImport.update({
  id: '/profil/karangtaruna',
  path: '/profil/karangtaruna',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilBpdRoute = ProfilBpdRouteImport.update({
  id: '/profil/bpd',
  path: '/profil/bpd',
  getParentRoute: () => rootRouteImport,
} as any)
const PelayananPendudukRoute = PelayananPendudukRouteImport.update({
  id: '/pelayanan/penduduk',
  path: '/pelayanan/penduduk',
  getParentRoute: () => rootRouteImport,
} as any)
const PelayananMonitoringRoute = PelayananMonitoringRouteImport.update({
  id: '/pelayanan/monitoring',
  path: '/pelayanan/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PelayananESuratRoute = PelayananESuratRouteImport.update({
  id: '/pelayanan/e-surat',
  path: '/pelayanan/e-surat',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanApbdesRoute = LaporanApbdesRouteImport.update({
  id: '/laporan/apbdes',
  path: '/laporan/apbdes',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaPetaRoute = LainnyaPetaRouteImport.update({
  id: '/lainnya/peta',
  path: '/lainnya/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiBeritaRoute = InformasiBeritaRouteImport.update({
  id: '/informasi/berita',
  path: '/informasi/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiAgendaRoute = InformasiAgendaRouteImport.update({
  id: '/informasi/agenda',
  path: '/informasi/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const EkonomiBumdesRoute = EkonomiBumdesRouteImport.update({
  id: '/ekonomi/bumdes',
  path: '/ekonomi/bumdes',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiBeritaSlugRoute = InformasiBeritaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InformasiBeritaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/ekonomi/bumdes': typeof EkonomiBumdesRoute
  '/informasi/agenda': typeof InformasiAgendaRoute
  '/informasi/berita': typeof InformasiBeritaRouteWithChildren
  '/lainnya/peta': typeof LainnyaPetaRoute
  '/laporan/apbdes': typeof LaporanApbdesRoute
  '/pelayanan/e-surat': typeof PelayananESuratRoute
  '/pelayanan/monitoring': typeof PelayananMonitoringRoute
  '/pelayanan/penduduk': typeof PelayananPendudukRoute
  '/profil/bpd': typeof ProfilBpdRoute
  '/profil/karangtaruna': typeof ProfilKarangtarunaRoute
  '/profil/lembaga': typeof ProfilLembagaRoute
  '/profil/lpm': typeof ProfilLpmRoute
  '/profil/perangkat': typeof ProfilPerangkatRoute
  '/profil/pkkrw': typeof ProfilPkkrwRoute
  '/verifikasi/$no': typeof VerifikasiNoRoute
  '/informasi/berita/$slug': typeof InformasiBeritaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/ekonomi/bumdes': typeof EkonomiBumdesRoute
  '/informasi/agenda': typeof InformasiAgendaRoute
  '/informasi/berita': typeof InformasiBeritaRouteWithChildren
  '/lainnya/peta': typeof LainnyaPetaRoute
  '/laporan/apbdes': typeof LaporanApbdesRoute
  '/pelayanan/e-surat': typeof PelayananESuratRoute
  '/pelayanan/monitoring': typeof PelayananMonitoringRoute
  '/pelayanan/penduduk': typeof PelayananPendudukRoute
  '/profil/bpd': typeof ProfilBpdRoute
  '/profil/karangtaruna': typeof ProfilKarangtarunaRoute
  '/profil/lembaga': typeof ProfilLembagaRoute
  '/profil/lpm': typeof ProfilLpmRoute
  '/profil/perangkat': typeof ProfilPerangkatRoute
  '/profil/pkkrw': typeof ProfilPkkrwRoute
  '/verifikasi/$no': typeof VerifikasiNoRoute
  '/informasi/berita/$slug': typeof InformasiBeritaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/ekonomi/bumdes': typeof EkonomiBumdesRoute
  '/informasi/agenda': typeof InformasiAgendaRoute
  '/informasi/berita': typeof InformasiBeritaRouteWithChildren
  '/lainnya/peta': typeof LainnyaPetaRoute
  '/laporan/apbdes': typeof LaporanApbdesRoute
  '/pelayanan/e-surat': typeof PelayananESuratRoute
  '/pelayanan/monitoring': typeof PelayananMonitoringRoute
  '/pelayanan/penduduk': typeof PelayananPendudukRoute
  '/profil/bpd': typeof ProfilBpdRoute
  '/profil/karangtaruna': typeof ProfilKarangtarunaRoute
  '/profil/lembaga': typeof ProfilLembagaRoute
  '/profil/lpm': typeof ProfilLpmRoute
  '/profil/perangkat': typeof ProfilPerangkatRoute
  '/profil/pkkrw': typeof ProfilPkkrwRoute
  '/verifikasi/$no': typeof VerifikasiNoRoute
  '/informasi/berita/$slug': typeof InformasiBeritaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/ekonomi/bumdes'
    | '/informasi/agenda'
    | '/informasi/berita'
    | '/lainnya/peta'
    | '/laporan/apbdes'
    | '/pelayanan/e-surat'
    | '/pelayanan/monitoring'
    | '/pelayanan/penduduk'
    | '/profil/bpd'
    | '/profil/karangtaruna'
    | '/profil/lembaga'
    | '/profil/lpm'
    | '/profil/perangkat'
    | '/profil/pkkrw'
    | '/verifikasi/$no'
    | '/informasi/berita/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/ekonomi/bumdes'
    | '/informasi/agenda'
    | '/informasi/berita'
    | '/lainnya/peta'
    | '/laporan/apbdes'
    | '/pelayanan/e-surat'
    | '/pelayanan/monitoring'
    | '/pelayanan/penduduk'
    | '/profil/bpd'
    | '/profil/karangtaruna'
    | '/profil/lembaga'
    | '/profil/lpm'
    | '/profil/perangkat'
    | '/profil/pkkrw'
    | '/verifikasi/$no'
    | '/informasi/berita/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/ekonomi/bumdes'
    | '/informasi/agenda'
    | '/informasi/berita'
    | '/lainnya/peta'
    | '/laporan/apbdes'
    | '/pelayanan/e-surat'
    | '/pelayanan/monitoring'
    | '/pelayanan/penduduk'
    | '/profil/bpd'
    | '/profil/karangtaruna'
    | '/profil/lembaga'
    | '/profil/lpm'
    | '/profil/perangkat'
    | '/profil/pkkrw'
    | '/verifikasi/$no'
    | '/informasi/berita/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  EkonomiBumdesRoute: typeof EkonomiBumdesRoute
  InformasiAgendaRoute: typeof InformasiAgendaRoute
  InformasiBeritaRoute: typeof InformasiBeritaRouteWithChildren
  LainnyaPetaRoute: typeof LainnyaPetaRoute
  LaporanApbdesRoute: typeof LaporanApbdesRoute
  PelayananESuratRoute: typeof PelayananESuratRoute
  PelayananMonitoringRoute: typeof PelayananMonitoringRoute
  PelayananPendudukRoute: typeof PelayananPendudukRoute
  ProfilBpdRoute: typeof ProfilBpdRoute
  ProfilKarangtarunaRoute: typeof ProfilKarangtarunaRoute
  ProfilLembagaRoute: typeof ProfilLembagaRoute
  ProfilLpmRoute: typeof ProfilLpmRoute
  ProfilPerangkatRoute: typeof ProfilPerangkatRoute
  ProfilPkkrwRoute: typeof ProfilPkkrwRoute
  VerifikasiNoRoute: typeof VerifikasiNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifikasi/$no': {
      id: '/verifikasi/$no'
      path: '/verifikasi/$no'
      fullPath: '/verifikasi/$no'
      preLoaderRoute: typeof VerifikasiNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/pkkrw': {
      id: '/profil/pkkrw'
      path: '/profil/pkkrw'
      fullPath: '/profil/pkkrw'
      preLoaderRoute: typeof ProfilPkkrwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/perangkat': {
      id: '/profil/perangkat'
      path: '/profil/perangkat'
      fullPath: '/profil/perangkat'
      preLoaderRoute: typeof ProfilPerangkatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/lpm': {
      id: '/profil/lpm'
      path: '/profil/lpm'
      fullPath: '/profil/lpm'
      preLoaderRoute: typeof ProfilLpmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/lembaga': {
      id: '/profil/lembaga'
      path: '/profil/lembaga'
      fullPath: '/profil/lembaga'
      preLoaderRoute: typeof ProfilLembagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/karangtaruna': {
      id: '/profil/karangtaruna'
      path: '/profil/karangtaruna'
      fullPath: '/profil/karangtaruna'
      preLoaderRoute: typeof ProfilKarangtarunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/bpd': {
      id: '/profil/bpd'
      path: '/profil/bpd'
      fullPath: '/profil/bpd'
      preLoaderRoute: typeof ProfilBpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelayanan/penduduk': {
      id: '/pelayanan/penduduk'
      path: '/pelayanan/penduduk'
      fullPath: '/pelayanan/penduduk'
      preLoaderRoute: typeof PelayananPendudukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelayanan/monitoring': {
      id: '/pelayanan/monitoring'
      path: '/pelayanan/monitoring'
      fullPath: '/pelayanan/monitoring'
      preLoaderRoute: typeof PelayananMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelayanan/e-surat': {
      id: '/pelayanan/e-surat'
      path: '/pelayanan/e-surat'
      fullPath: '/pelayanan/e-surat'
      preLoaderRoute: typeof PelayananESuratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/apbdes': {
      id: '/laporan/apbdes'
      path: '/laporan/apbdes'
      fullPath: '/laporan/apbdes'
      preLoaderRoute: typeof LaporanApbdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya/peta': {
      id: '/lainnya/peta'
      path: '/lainnya/peta'
      fullPath: '/lainnya/peta'
      preLoaderRoute: typeof LainnyaPetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/berita': {
      id: '/informasi/berita'
      path: '/informasi/berita'
      fullPath: '/informasi/berita'
      preLoaderRoute: typeof InformasiBeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/agenda': {
      id: '/informasi/agenda'
      path: '/informasi/agenda'
      fullPath: '/informasi/agenda'
      preLoaderRoute: typeof InformasiAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekonomi/bumdes': {
      id: '/ekonomi/bumdes'
      path: '/ekonomi/bumdes'
      fullPath: '/ekonomi/bumdes'
      preLoaderRoute: typeof EkonomiBumdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/berita/$slug': {
      id: '/informasi/berita/$slug'
      path: '/$slug'
      fullPath: '/informasi/berita/$slug'
      preLoaderRoute: typeof InformasiBeritaSlugRouteImport
      parentRoute: typeof InformasiBeritaRoute
    }
  }
}

interface InformasiBeritaRouteChildren {
  InformasiBeritaSlugRoute: typeof InformasiBeritaSlugRoute
}

const InformasiBeritaRouteChildren: InformasiBeritaRouteChildren = {
  InformasiBeritaSlugRoute: InformasiBeritaSlugRoute,
}

const InformasiBeritaRouteWithChildren = InformasiBeritaRoute._addFileChildren(
  InformasiBeritaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  EkonomiBumdesRoute: EkonomiBumdesRoute,
  InformasiAgendaRoute: InformasiAgendaRoute,
  InformasiBeritaRoute: InformasiBeritaRouteWithChildren,
  LainnyaPetaRoute: LainnyaPetaRoute,
  LaporanApbdesRoute: LaporanApbdesRoute,
  PelayananESuratRoute: PelayananESuratRoute,
  PelayananMonitoringRoute: PelayananMonitoringRoute,
  PelayananPendudukRoute: PelayananPendudukRoute,
  ProfilBpdRoute: ProfilBpdRoute,
  ProfilKarangtarunaRoute: ProfilKarangtarunaRoute,
  ProfilLembagaRoute: ProfilLembagaRoute,
  ProfilLpmRoute: ProfilLpmRoute,
  ProfilPerangkatRoute: ProfilPerangkatRoute,
  ProfilPkkrwRoute: ProfilPkkrwRoute,
  VerifikasiNoRoute: VerifikasiNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
